/* CompTIA Security+ SY0-701 -- objective tags per question.
   GENERATED by tools/classify_objectives.py -- do not hand-edit;
   add corrections to MANUAL_TAGS in that script instead.
   1003 of 1003 questions tagged.
   o = objective id, c = confidence (high|low). Untagged questions
   appear in the app under 'Unsorted' and are listed in
   tools/objective-review.md. */
window.OBJECTIVE_META = {
  "1.1": {
    "name": "Compare and contrast various types of security controls.",
    "domain": "1.0"
  },
  "1.2": {
    "name": "Summarize fundamental security concepts.",
    "domain": "1.0"
  },
  "1.3": {
    "name": "Explain the importance of change management processes and the impact to security.",
    "domain": "1.0"
  },
  "1.4": {
    "name": "Explain the importance of using appropriate cryptographic solutions.",
    "domain": "1.0"
  },
  "2.1": {
    "name": "Compare and contrast common threat actors and motivations.",
    "domain": "2.0"
  },
  "2.2": {
    "name": "Explain common threat vectors and attack surfaces.",
    "domain": "2.0"
  },
  "2.3": {
    "name": "Explain various types of vulnerabilities.",
    "domain": "2.0"
  },
  "2.4": {
    "name": "Given a scenario, analyze indicators of malicious activity.",
    "domain": "2.0"
  },
  "2.5": {
    "name": "Explain the purpose of mitigation techniques used to secure the enterprise.",
    "domain": "2.0"
  },
  "3.1": {
    "name": "Compare and contrast security implications of different architecture models.",
    "domain": "3.0"
  },
  "3.2": {
    "name": "Given a scenario, apply security principles to secure enterprise infrastructure.",
    "domain": "3.0"
  },
  "3.3": {
    "name": "Compare and contrast concepts and strategies to protect data.",
    "domain": "3.0"
  },
  "3.4": {
    "name": "Explain the importance of resilience and recovery in security architecture.",
    "domain": "3.0"
  },
  "4.1": {
    "name": "Given a scenario, apply common security techniques to computing resources.",
    "domain": "4.0"
  },
  "4.2": {
    "name": "Explain the security implications of proper hardware, software, and data asset management.",
    "domain": "4.0"
  },
  "4.3": {
    "name": "Explain various activities associated with vulnerability management.",
    "domain": "4.0"
  },
  "4.4": {
    "name": "Explain security alerting and monitoring concepts and tools.",
    "domain": "4.0"
  },
  "4.5": {
    "name": "Given a scenario, modify enterprise capabilities to enhance security.",
    "domain": "4.0"
  },
  "4.6": {
    "name": "Given a scenario, implement and maintain identity and access management.",
    "domain": "4.0"
  },
  "4.7": {
    "name": "Explain the importance of automation and orchestration related to secure operations.",
    "domain": "4.0"
  },
  "4.8": {
    "name": "Explain appropriate incident response activities.",
    "domain": "4.0"
  },
  "4.9": {
    "name": "Given a scenario, use data sources to support an investigation.",
    "domain": "4.0"
  },
  "5.1": {
    "name": "Summarize elements of effective security governance.",
    "domain": "5.0"
  },
  "5.2": {
    "name": "Explain elements of the risk management process.",
    "domain": "5.0"
  },
  "5.3": {
    "name": "Explain the processes associated with third-party risk assessment and management.",
    "domain": "5.0"
  },
  "5.4": {
    "name": "Summarize elements of effective security compliance.",
    "domain": "5.0"
  },
  "5.5": {
    "name": "Explain types and purposes of audits and assessments.",
    "domain": "5.0"
  },
  "5.6": {
    "name": "Given a scenario, implement security awareness practices.",
    "domain": "5.0"
  }
};
window.QUESTION_OBJECTIVES = {
  "SEC-D1-001": {
    "o": "1.4",
    "c": "high"
  },
  "SEC-D1-002": {
    "o": "1.4",
    "c": "high"
  },
  "SEC-D1-003": {
    "o": "1.2",
    "c": "high"
  },
  "SEC-D1-004": {
    "o": "1.3",
    "c": "high"
  },
  "SEC-D1-005": {
    "o": "1.3",
    "c": "high"
  },
  "SEC-D1-006": {
    "o": "1.4",
    "c": "high"
  },
  "SEC-D1-007": {
    "o": "1.1",
    "c": "high"
  },
  "SEC-D1-008": {
    "o": "1.4",
    "c": "low"
  },
  "SEC-D1-009": {
    "o": "1.4",
    "c": "high"
  },
  "SEC-D1-010": {
    "o": "1.3",
    "c": "high"
  },
  "SEC-D1-011": {
    "o": "1.3",
    "c": "high"
  },
  "SEC-D1-012": {
    "o": "1.2",
    "c": "high"
  },
  "SEC-D1-013": {
    "o": "1.1",
    "c": "high"
  },
  "SEC-D1-014": {
    "o": "1.1",
    "c": "high"
  },
  "SEC-D1-015": {
    "o": "1.1",
    "c": "high"
  },
  "SEC-D1-016": {
    "o": "1.2",
    "c": "high"
  },
  "SEC-D1-017": {
    "o": "1.4",
    "c": "high"
  },
  "SEC-D1-018": {
    "o": "1.4",
    "c": "high"
  },
  "SEC-D1-019": {
    "o": "1.4",
    "c": "high"
  },
  "SEC-D1-020": {
    "o": "1.3",
    "c": "high"
  },
  "SEC-D1-021": {
    "o": "1.3",
    "c": "high"
  },
  "SEC-D1-022": {
    "o": "1.3",
    "c": "high"
  },
  "SEC-D1-023": {
    "o": "1.2",
    "c": "high"
  },
  "SEC-D1-024": {
    "o": "1.4",
    "c": "high"
  },
  "SEC-D1-025": {
    "o": "1.3",
    "c": "high"
  },
  "SEC-D1-026": {
    "o": "1.3",
    "c": "high"
  },
  "SEC-D1-027": {
    "o": "1.4",
    "c": "high"
  },
  "SEC-D1-028": {
    "o": "1.4",
    "c": "high"
  },
  "SEC-D1-029": {
    "o": "1.4",
    "c": "high"
  },
  "SEC-D1-030": {
    "o": "1.1",
    "c": "high"
  },
  "SEC-D1-031": {
    "o": "1.4",
    "c": "high"
  },
  "SEC-D1-032": {
    "o": "1.3",
    "c": "high"
  },
  "SEC-D1-033": {
    "o": "1.4",
    "c": "low"
  },
  "SEC-D1-034": {
    "o": "1.2",
    "c": "high"
  },
  "SEC-D1-035": {
    "o": "1.2",
    "c": "high"
  },
  "SEC-D1-036": {
    "o": "1.2",
    "c": "high"
  },
  "SEC-D1-037": {
    "o": "1.2",
    "c": "manual"
  },
  "SEC-D1-038": {
    "o": "1.2",
    "c": "high"
  },
  "SEC-D1-039": {
    "o": "1.2",
    "c": "low"
  },
  "SEC-D1-040": {
    "o": "1.3",
    "c": "high"
  },
  "SEC-D1-041": {
    "o": "1.2",
    "c": "high"
  },
  "SEC-D1-042": {
    "o": "1.3",
    "c": "high"
  },
  "SEC-D1-043": {
    "o": "1.4",
    "c": "low"
  },
  "SEC-D1-044": {
    "o": "1.4",
    "c": "high"
  },
  "SEC-D1-045": {
    "o": "1.4",
    "c": "high"
  },
  "SEC-D1-046": {
    "o": "1.3",
    "c": "high"
  },
  "SEC-D1-047": {
    "o": "1.3",
    "c": "high"
  },
  "SEC-D1-048": {
    "o": "1.3",
    "c": "high"
  },
  "SEC-D1-049": {
    "o": "1.4",
    "c": "high"
  },
  "SEC-D1-050": {
    "o": "1.4",
    "c": "high"
  },
  "SEC-D1-051": {
    "o": "1.4",
    "c": "high"
  },
  "SEC-D1-052": {
    "o": "1.4",
    "c": "high"
  },
  "SEC-D1-053": {
    "o": "1.4",
    "c": "low"
  },
  "SEC-D1-054": {
    "o": "1.4",
    "c": "high"
  },
  "SEC-D1-055": {
    "o": "1.4",
    "c": "high"
  },
  "SEC-D1-056": {
    "o": "1.2",
    "c": "low"
  },
  "SEC-D1-057": {
    "o": "1.2",
    "c": "high"
  },
  "SEC-D1-058": {
    "o": "1.1",
    "c": "high"
  },
  "SEC-D1-059": {
    "o": "1.2",
    "c": "low"
  },
  "SEC-D1-060": {
    "o": "1.4",
    "c": "high"
  },
  "SEC-D1-061": {
    "o": "1.1",
    "c": "high"
  },
  "SEC-D1-062": {
    "o": "1.2",
    "c": "high"
  },
  "SEC-D1-063": {
    "o": "1.2",
    "c": "high"
  },
  "SEC-D1-064": {
    "o": "1.2",
    "c": "high"
  },
  "SEC-D1-065": {
    "o": "1.2",
    "c": "high"
  },
  "SEC-D1-066": {
    "o": "1.2",
    "c": "high"
  },
  "SEC-D1-067": {
    "o": "1.1",
    "c": "high"
  },
  "SEC-D1-068": {
    "o": "1.4",
    "c": "high"
  },
  "SEC-D1-069": {
    "o": "1.4",
    "c": "high"
  },
  "SEC-D1-070": {
    "o": "1.4",
    "c": "high"
  },
  "SEC-D1-071": {
    "o": "1.4",
    "c": "low"
  },
  "SEC-D1-072": {
    "o": "1.4",
    "c": "low"
  },
  "SEC-D1-073": {
    "o": "1.2",
    "c": "high"
  },
  "SEC-D1-074": {
    "o": "1.1",
    "c": "high"
  },
  "SEC-D1-075": {
    "o": "1.4",
    "c": "high"
  },
  "SEC-D1-076": {
    "o": "1.2",
    "c": "manual"
  },
  "SEC-D1-077": {
    "o": "1.2",
    "c": "low"
  },
  "SEC-D1-078": {
    "o": "1.1",
    "c": "high"
  },
  "SEC-D1-079": {
    "o": "1.4",
    "c": "high"
  },
  "SEC-D1-080": {
    "o": "1.2",
    "c": "low"
  },
  "SEC-D1-081": {
    "o": "1.4",
    "c": "high"
  },
  "SEC-D1-082": {
    "o": "1.3",
    "c": "high"
  },
  "SEC-D1-083": {
    "o": "1.2",
    "c": "high"
  },
  "SEC-D1-084": {
    "o": "1.4",
    "c": "high"
  },
  "SEC-D1-085": {
    "o": "1.1",
    "c": "high"
  },
  "SEC-D1-086": {
    "o": "1.4",
    "c": "high"
  },
  "SEC-D1-087": {
    "o": "1.4",
    "c": "high"
  },
  "SEC-D1-088": {
    "o": "1.4",
    "c": "high"
  },
  "SEC-D1-089": {
    "o": "1.4",
    "c": "high"
  },
  "SEC-D1-090": {
    "o": "1.3",
    "c": "high"
  },
  "SEC-D1-091": {
    "o": "1.1",
    "c": "high"
  },
  "SEC-D1-092": {
    "o": "1.2",
    "c": "low"
  },
  "SEC-D1-093": {
    "o": "1.2",
    "c": "high"
  },
  "SEC-D1-094": {
    "o": "1.4",
    "c": "low"
  },
  "SEC-D1-095": {
    "o": "1.4",
    "c": "manual"
  },
  "SEC-D1-096": {
    "o": "1.4",
    "c": "high"
  },
  "SEC-D1-097": {
    "o": "1.2",
    "c": "high"
  },
  "SEC-D1-098": {
    "o": "1.1",
    "c": "high"
  },
  "SEC-D1-099": {
    "o": "1.2",
    "c": "high"
  },
  "SEC-D1-100": {
    "o": "1.4",
    "c": "low"
  },
  "SEC-D1-101": {
    "o": "1.2",
    "c": "high"
  },
  "SEC-D1-102": {
    "o": "1.2",
    "c": "high"
  },
  "SEC-D1-103": {
    "o": "1.4",
    "c": "high"
  },
  "SEC-D1-104": {
    "o": "1.3",
    "c": "high"
  },
  "SEC-D1-105": {
    "o": "1.3",
    "c": "high"
  },
  "SEC-D1-106": {
    "o": "1.4",
    "c": "low"
  },
  "SEC-D1-107": {
    "o": "1.4",
    "c": "high"
  },
  "SEC-D1-108": {
    "o": "1.4",
    "c": "high"
  },
  "SEC-D1-109": {
    "o": "1.4",
    "c": "high"
  },
  "SEC-D1-110": {
    "o": "1.4",
    "c": "high"
  },
  "SEC-D1-111": {
    "o": "1.1",
    "c": "high"
  },
  "SEC-D1-112": {
    "o": "1.3",
    "c": "high"
  },
  "SEC-D1-113": {
    "o": "1.2",
    "c": "high"
  },
  "SEC-D1-114": {
    "o": "1.3",
    "c": "high"
  },
  "SEC-D1-115": {
    "o": "1.2",
    "c": "high"
  },
  "SEC-D1-116": {
    "o": "1.2",
    "c": "low"
  },
  "SEC-D1-117": {
    "o": "1.2",
    "c": "high"
  },
  "SEC-D1-118": {
    "o": "1.2",
    "c": "high"
  },
  "SEC-D1-119": {
    "o": "1.1",
    "c": "high"
  },
  "SEC-D1-120": {
    "o": "1.2",
    "c": "high"
  },
  "SEC-D1-121": {
    "o": "1.1",
    "c": "high"
  },
  "SEC-D1-122": {
    "o": "1.4",
    "c": "high"
  },
  "SEC-D1-123": {
    "o": "1.4",
    "c": "high"
  },
  "SEC-D1-124": {
    "o": "1.3",
    "c": "high"
  },
  "SEC-D1-125": {
    "o": "1.4",
    "c": "high"
  },
  "SEC-D1-126": {
    "o": "1.4",
    "c": "high"
  },
  "SEC-D1-127": {
    "o": "1.4",
    "c": "low"
  },
  "SEC-D1-128": {
    "o": "1.4",
    "c": "high"
  },
  "SEC-D1-129": {
    "o": "1.3",
    "c": "high"
  },
  "SEC-D1-130": {
    "o": "1.3",
    "c": "high"
  },
  "SEC-D1-131": {
    "o": "1.4",
    "c": "high"
  },
  "SEC-D1-132": {
    "o": "1.2",
    "c": "high"
  },
  "SEC-D1-133": {
    "o": "1.2",
    "c": "high"
  },
  "SEC-D1-134": {
    "o": "1.4",
    "c": "high"
  },
  "SEC-D1-135": {
    "o": "1.4",
    "c": "high"
  },
  "SEC-D1-136": {
    "o": "1.4",
    "c": "high"
  },
  "SEC-D1-137": {
    "o": "1.4",
    "c": "high"
  },
  "SEC-D1-138": {
    "o": "1.3",
    "c": "low"
  },
  "SEC-D1-139": {
    "o": "1.2",
    "c": "high"
  },
  "SEC-D1-140": {
    "o": "1.2",
    "c": "high"
  },
  "SEC-D1-141": {
    "o": "1.2",
    "c": "low"
  },
  "SEC-D1-142": {
    "o": "1.2",
    "c": "high"
  },
  "SEC-D1-143": {
    "o": "1.2",
    "c": "high"
  },
  "SEC-D1-144": {
    "o": "1.4",
    "c": "high"
  },
  "SEC-D1-145": {
    "o": "1.4",
    "c": "high"
  },
  "SEC-D1-146": {
    "o": "1.4",
    "c": "high"
  },
  "SEC-D1-147": {
    "o": "1.1",
    "c": "low"
  },
  "SEC-D1-148": {
    "o": "1.1",
    "c": "high"
  },
  "SEC-D1-149": {
    "o": "1.4",
    "c": "high"
  },
  "SEC-D1-150": {
    "o": "1.2",
    "c": "high"
  },
  "SEC-D2-001": {
    "o": "2.1",
    "c": "high"
  },
  "SEC-D2-002": {
    "o": "2.2",
    "c": "high"
  },
  "SEC-D2-003": {
    "o": "2.4",
    "c": "high"
  },
  "SEC-D2-004": {
    "o": "2.3",
    "c": "high"
  },
  "SEC-D2-005": {
    "o": "2.3",
    "c": "high"
  },
  "SEC-D2-006": {
    "o": "2.5",
    "c": "high"
  },
  "SEC-D2-007": {
    "o": "2.2",
    "c": "low"
  },
  "SEC-D2-008": {
    "o": "2.3",
    "c": "high"
  },
  "SEC-D2-009": {
    "o": "2.4",
    "c": "low"
  },
  "SEC-D2-010": {
    "o": "2.4",
    "c": "high"
  },
  "SEC-D2-011": {
    "o": "2.4",
    "c": "low"
  },
  "SEC-D2-012": {
    "o": "2.2",
    "c": "high"
  },
  "SEC-D2-013": {
    "o": "2.3",
    "c": "high"
  },
  "SEC-D2-014": {
    "o": "2.4",
    "c": "high"
  },
  "SEC-D2-015": {
    "o": "2.1",
    "c": "high"
  },
  "SEC-D2-016": {
    "o": "2.2",
    "c": "high"
  },
  "SEC-D2-017": {
    "o": "2.4",
    "c": "high"
  },
  "SEC-D2-018": {
    "o": "2.4",
    "c": "high"
  },
  "SEC-D2-019": {
    "o": "2.2",
    "c": "high"
  },
  "SEC-D2-020": {
    "o": "2.3",
    "c": "high"
  },
  "SEC-D2-021": {
    "o": "2.3",
    "c": "low"
  },
  "SEC-D2-022": {
    "o": "2.3",
    "c": "low"
  },
  "SEC-D2-023": {
    "o": "2.2",
    "c": "low"
  },
  "SEC-D2-024": {
    "o": "2.5",
    "c": "high"
  },
  "SEC-D2-025": {
    "o": "2.5",
    "c": "high"
  },
  "SEC-D2-026": {
    "o": "2.1",
    "c": "high"
  },
  "SEC-D2-027": {
    "o": "2.2",
    "c": "high"
  },
  "SEC-D2-028": {
    "o": "2.2",
    "c": "low"
  },
  "SEC-D2-029": {
    "o": "2.4",
    "c": "high"
  },
  "SEC-D2-030": {
    "o": "2.4",
    "c": "high"
  },
  "SEC-D2-031": {
    "o": "2.1",
    "c": "high"
  },
  "SEC-D2-032": {
    "o": "2.1",
    "c": "high"
  },
  "SEC-D2-033": {
    "o": "2.2",
    "c": "low"
  },
  "SEC-D2-034": {
    "o": "2.4",
    "c": "low"
  },
  "SEC-D2-035": {
    "o": "2.2",
    "c": "high"
  },
  "SEC-D2-036": {
    "o": "2.3",
    "c": "low"
  },
  "SEC-D2-037": {
    "o": "2.5",
    "c": "high"
  },
  "SEC-D2-038": {
    "o": "2.2",
    "c": "high"
  },
  "SEC-D2-039": {
    "o": "2.5",
    "c": "high"
  },
  "SEC-D2-040": {
    "o": "2.2",
    "c": "low"
  },
  "SEC-D2-041": {
    "o": "2.4",
    "c": "high"
  },
  "SEC-D2-042": {
    "o": "2.4",
    "c": "high"
  },
  "SEC-D2-043": {
    "o": "2.4",
    "c": "high"
  },
  "SEC-D2-044": {
    "o": "2.2",
    "c": "high"
  },
  "SEC-D2-045": {
    "o": "2.4",
    "c": "high"
  },
  "SEC-D2-046": {
    "o": "2.2",
    "c": "low"
  },
  "SEC-D2-047": {
    "o": "2.5",
    "c": "high"
  },
  "SEC-D2-048": {
    "o": "2.1",
    "c": "high"
  },
  "SEC-D2-049": {
    "o": "2.4",
    "c": "high"
  },
  "SEC-D2-050": {
    "o": "2.5",
    "c": "low"
  },
  "SEC-D2-051": {
    "o": "2.5",
    "c": "manual"
  },
  "SEC-D2-052": {
    "o": "2.5",
    "c": "high"
  },
  "SEC-D2-053": {
    "o": "2.5",
    "c": "manual"
  },
  "SEC-D2-055": {
    "o": "2.5",
    "c": "low"
  },
  "SEC-D2-056": {
    "o": "2.5",
    "c": "high"
  },
  "SEC-D2-057": {
    "o": "2.4",
    "c": "low"
  },
  "SEC-D2-058": {
    "o": "2.4",
    "c": "high"
  },
  "SEC-D2-059": {
    "o": "2.4",
    "c": "high"
  },
  "SEC-D2-060": {
    "o": "2.3",
    "c": "low"
  },
  "SEC-D2-061": {
    "o": "2.2",
    "c": "high"
  },
  "SEC-D2-062": {
    "o": "2.2",
    "c": "high"
  },
  "SEC-D2-063": {
    "o": "2.3",
    "c": "high"
  },
  "SEC-D2-064": {
    "o": "2.2",
    "c": "high"
  },
  "SEC-D2-065": {
    "o": "2.2",
    "c": "high"
  },
  "SEC-D2-066": {
    "o": "2.4",
    "c": "low"
  },
  "SEC-D2-067": {
    "o": "2.4",
    "c": "high"
  },
  "SEC-D2-068": {
    "o": "2.2",
    "c": "high"
  },
  "SEC-D2-069": {
    "o": "2.4",
    "c": "high"
  },
  "SEC-D2-070": {
    "o": "2.4",
    "c": "low"
  },
  "SEC-D2-071": {
    "o": "2.5",
    "c": "high"
  },
  "SEC-D2-072": {
    "o": "2.5",
    "c": "high"
  },
  "SEC-D2-073": {
    "o": "2.3",
    "c": "high"
  },
  "SEC-D2-074": {
    "o": "2.4",
    "c": "high"
  },
  "SEC-D2-075": {
    "o": "2.4",
    "c": "high"
  },
  "SEC-D2-076": {
    "o": "2.3",
    "c": "low"
  },
  "SEC-D2-077": {
    "o": "2.4",
    "c": "low"
  },
  "SEC-D2-078": {
    "o": "2.4",
    "c": "low"
  },
  "SEC-D2-079": {
    "o": "2.1",
    "c": "high"
  },
  "SEC-D2-080": {
    "o": "2.3",
    "c": "low"
  },
  "SEC-D2-081": {
    "o": "2.5",
    "c": "high"
  },
  "SEC-D2-082": {
    "o": "2.4",
    "c": "low"
  },
  "SEC-D2-083": {
    "o": "2.3",
    "c": "low"
  },
  "SEC-D2-084": {
    "o": "2.3",
    "c": "high"
  },
  "SEC-D2-085": {
    "o": "2.1",
    "c": "high"
  },
  "SEC-D2-086": {
    "o": "2.4",
    "c": "high"
  },
  "SEC-D2-087": {
    "o": "2.1",
    "c": "low"
  },
  "SEC-D2-088": {
    "o": "2.2",
    "c": "high"
  },
  "SEC-D2-089": {
    "o": "2.1",
    "c": "high"
  },
  "SEC-D2-090": {
    "o": "2.4",
    "c": "high"
  },
  "SEC-D2-091": {
    "o": "2.1",
    "c": "high"
  },
  "SEC-D2-092": {
    "o": "2.2",
    "c": "high"
  },
  "SEC-D2-093": {
    "o": "2.4",
    "c": "high"
  },
  "SEC-D2-094": {
    "o": "2.4",
    "c": "low"
  },
  "SEC-D2-095": {
    "o": "2.4",
    "c": "high"
  },
  "SEC-D2-096": {
    "o": "2.3",
    "c": "low"
  },
  "SEC-D2-097": {
    "o": "2.4",
    "c": "low"
  },
  "SEC-D2-098": {
    "o": "2.1",
    "c": "high"
  },
  "SEC-D2-099": {
    "o": "2.3",
    "c": "high"
  },
  "SEC-D2-100": {
    "o": "2.4",
    "c": "high"
  },
  "SEC-D2-101": {
    "o": "2.2",
    "c": "high"
  },
  "SEC-D2-102": {
    "o": "2.1",
    "c": "high"
  },
  "SEC-D2-103": {
    "o": "2.2",
    "c": "high"
  },
  "SEC-D2-104": {
    "o": "2.4",
    "c": "high"
  },
  "SEC-D2-105": {
    "o": "2.4",
    "c": "low"
  },
  "SEC-D2-106": {
    "o": "2.3",
    "c": "low"
  },
  "SEC-D2-107": {
    "o": "2.2",
    "c": "high"
  },
  "SEC-D2-108": {
    "o": "2.4",
    "c": "high"
  },
  "SEC-D2-109": {
    "o": "2.4",
    "c": "high"
  },
  "SEC-D2-110": {
    "o": "2.4",
    "c": "manual"
  },
  "SEC-D2-111": {
    "o": "2.2",
    "c": "low"
  },
  "SEC-D2-112": {
    "o": "2.3",
    "c": "high"
  },
  "SEC-D2-113": {
    "o": "2.3",
    "c": "low"
  },
  "SEC-D2-114": {
    "o": "2.5",
    "c": "manual"
  },
  "SEC-D2-115": {
    "o": "2.4",
    "c": "low"
  },
  "SEC-D2-116": {
    "o": "2.4",
    "c": "high"
  },
  "SEC-D2-117": {
    "o": "2.2",
    "c": "high"
  },
  "SEC-D2-118": {
    "o": "2.3",
    "c": "high"
  },
  "SEC-D2-119": {
    "o": "2.1",
    "c": "high"
  },
  "SEC-D2-120": {
    "o": "2.5",
    "c": "manual"
  },
  "SEC-D2-121": {
    "o": "2.4",
    "c": "low"
  },
  "SEC-D2-122": {
    "o": "2.4",
    "c": "high"
  },
  "SEC-D2-123": {
    "o": "2.3",
    "c": "high"
  },
  "SEC-D2-124": {
    "o": "2.3",
    "c": "high"
  },
  "SEC-D2-125": {
    "o": "2.4",
    "c": "low"
  },
  "SEC-D2-126": {
    "o": "2.5",
    "c": "high"
  },
  "SEC-D2-127": {
    "o": "2.1",
    "c": "high"
  },
  "SEC-D2-128": {
    "o": "2.3",
    "c": "low"
  },
  "SEC-D2-129": {
    "o": "2.5",
    "c": "high"
  },
  "SEC-D2-130": {
    "o": "2.5",
    "c": "low"
  },
  "SEC-D2-131": {
    "o": "2.3",
    "c": "low"
  },
  "SEC-D2-132": {
    "o": "2.3",
    "c": "high"
  },
  "SEC-D2-133": {
    "o": "2.4",
    "c": "high"
  },
  "SEC-D2-134": {
    "o": "2.5",
    "c": "manual"
  },
  "SEC-D2-135": {
    "o": "2.4",
    "c": "high"
  },
  "SEC-D2-136": {
    "o": "2.4",
    "c": "high"
  },
  "SEC-D2-137": {
    "o": "2.5",
    "c": "high"
  },
  "SEC-D2-138": {
    "o": "2.2",
    "c": "high"
  },
  "SEC-D2-139": {
    "o": "2.2",
    "c": "low"
  },
  "SEC-D2-140": {
    "o": "2.2",
    "c": "high"
  },
  "SEC-D2-141": {
    "o": "2.4",
    "c": "high"
  },
  "SEC-D2-142": {
    "o": "2.4",
    "c": "high"
  },
  "SEC-D2-143": {
    "o": "2.1",
    "c": "high"
  },
  "SEC-D2-144": {
    "o": "2.4",
    "c": "low"
  },
  "SEC-D2-145": {
    "o": "2.3",
    "c": "low"
  },
  "SEC-D2-146": {
    "o": "2.4",
    "c": "high"
  },
  "SEC-D2-147": {
    "o": "2.5",
    "c": "manual"
  },
  "SEC-D2-148": {
    "o": "2.4",
    "c": "low"
  },
  "SEC-D2-149": {
    "o": "2.3",
    "c": "high"
  },
  "SEC-D2-150": {
    "o": "2.4",
    "c": "high"
  },
  "SEC-D2-151": {
    "o": "2.4",
    "c": "high"
  },
  "SEC-D2-152": {
    "o": "2.4",
    "c": "high"
  },
  "SEC-D2-153": {
    "o": "2.3",
    "c": "high"
  },
  "SEC-D2-154": {
    "o": "2.2",
    "c": "high"
  },
  "SEC-D2-155": {
    "o": "2.2",
    "c": "high"
  },
  "SEC-D2-156": {
    "o": "2.2",
    "c": "high"
  },
  "SEC-D2-157": {
    "o": "2.3",
    "c": "high"
  },
  "SEC-D2-158": {
    "o": "2.4",
    "c": "high"
  },
  "SEC-D2-160": {
    "o": "2.5",
    "c": "high"
  },
  "SEC-D2-161": {
    "o": "2.2",
    "c": "high"
  },
  "SEC-D2-162": {
    "o": "2.4",
    "c": "high"
  },
  "SEC-D2-163": {
    "o": "2.1",
    "c": "high"
  },
  "SEC-D2-164": {
    "o": "2.3",
    "c": "low"
  },
  "SEC-D2-165": {
    "o": "2.4",
    "c": "manual"
  },
  "SEC-D2-166": {
    "o": "2.5",
    "c": "high"
  },
  "SEC-D2-167": {
    "o": "2.4",
    "c": "high"
  },
  "SEC-D2-168": {
    "o": "2.1",
    "c": "high"
  },
  "SEC-D2-169": {
    "o": "2.3",
    "c": "manual"
  },
  "SEC-D2-170": {
    "o": "2.4",
    "c": "high"
  },
  "SEC-D2-171": {
    "o": "2.2",
    "c": "low"
  },
  "SEC-D2-172": {
    "o": "2.5",
    "c": "high"
  },
  "SEC-D2-173": {
    "o": "2.5",
    "c": "manual"
  },
  "SEC-D2-174": {
    "o": "2.4",
    "c": "high"
  },
  "SEC-D2-175": {
    "o": "2.4",
    "c": "high"
  },
  "SEC-D2-176": {
    "o": "2.4",
    "c": "low"
  },
  "SEC-D2-177": {
    "o": "2.4",
    "c": "high"
  },
  "SEC-D2-178": {
    "o": "2.4",
    "c": "high"
  },
  "SEC-D2-179": {
    "o": "2.4",
    "c": "high"
  },
  "SEC-D2-180": {
    "o": "2.4",
    "c": "high"
  },
  "SEC-D2-181": {
    "o": "2.4",
    "c": "high"
  },
  "SEC-D2-182": {
    "o": "2.3",
    "c": "high"
  },
  "SEC-D2-183": {
    "o": "2.2",
    "c": "low"
  },
  "SEC-D2-184": {
    "o": "2.5",
    "c": "high"
  },
  "SEC-D2-185": {
    "o": "2.3",
    "c": "high"
  },
  "SEC-D2-186": {
    "o": "2.4",
    "c": "high"
  },
  "SEC-D2-187": {
    "o": "2.3",
    "c": "high"
  },
  "SEC-D3-001": {
    "o": "3.4",
    "c": "high"
  },
  "SEC-D3-002": {
    "o": "3.2",
    "c": "high"
  },
  "SEC-D3-003": {
    "o": "3.4",
    "c": "high"
  },
  "SEC-D3-004": {
    "o": "3.1",
    "c": "high"
  },
  "SEC-D3-005": {
    "o": "3.4",
    "c": "high"
  },
  "SEC-D3-006": {
    "o": "3.1",
    "c": "high"
  },
  "SEC-D3-007": {
    "o": "3.1",
    "c": "high"
  },
  "SEC-D3-008": {
    "o": "3.1",
    "c": "high"
  },
  "SEC-D3-009": {
    "o": "3.1",
    "c": "high"
  },
  "SEC-D3-010": {
    "o": "3.1",
    "c": "high"
  },
  "SEC-D3-011": {
    "o": "3.1",
    "c": "high"
  },
  "SEC-D3-012": {
    "o": "3.1",
    "c": "high"
  },
  "SEC-D3-013": {
    "o": "3.1",
    "c": "high"
  },
  "SEC-D3-014": {
    "o": "3.1",
    "c": "high"
  },
  "SEC-D3-015": {
    "o": "3.4",
    "c": "high"
  },
  "SEC-D3-016": {
    "o": "3.1",
    "c": "high"
  },
  "SEC-D3-017": {
    "o": "3.4",
    "c": "high"
  },
  "SEC-D3-018": {
    "o": "3.1",
    "c": "high"
  },
  "SEC-D3-019": {
    "o": "3.2",
    "c": "high"
  },
  "SEC-D3-020": {
    "o": "3.4",
    "c": "high"
  },
  "SEC-D3-021": {
    "o": "3.3",
    "c": "high"
  },
  "SEC-D3-022": {
    "o": "3.1",
    "c": "high"
  },
  "SEC-D3-023": {
    "o": "3.4",
    "c": "high"
  },
  "SEC-D3-024": {
    "o": "3.2",
    "c": "high"
  },
  "SEC-D3-025": {
    "o": "3.2",
    "c": "high"
  },
  "SEC-D3-026": {
    "o": "3.2",
    "c": "high"
  },
  "SEC-D3-027": {
    "o": "3.2",
    "c": "high"
  },
  "SEC-D3-028": {
    "o": "3.2",
    "c": "low"
  },
  "SEC-D3-029": {
    "o": "3.2",
    "c": "high"
  },
  "SEC-D3-030": {
    "o": "3.2",
    "c": "high"
  },
  "SEC-D3-031": {
    "o": "3.2",
    "c": "low"
  },
  "SEC-D3-032": {
    "o": "3.2",
    "c": "low"
  },
  "SEC-D3-033": {
    "o": "3.2",
    "c": "high"
  },
  "SEC-D3-034": {
    "o": "3.3",
    "c": "high"
  },
  "SEC-D3-035": {
    "o": "3.2",
    "c": "high"
  },
  "SEC-D3-036": {
    "o": "3.2",
    "c": "high"
  },
  "SEC-D3-037": {
    "o": "3.2",
    "c": "high"
  },
  "SEC-D3-038": {
    "o": "3.2",
    "c": "high"
  },
  "SEC-D3-039": {
    "o": "3.2",
    "c": "low"
  },
  "SEC-D3-040": {
    "o": "3.2",
    "c": "high"
  },
  "SEC-D3-041": {
    "o": "3.2",
    "c": "high"
  },
  "SEC-D3-042": {
    "o": "3.2",
    "c": "high"
  },
  "SEC-D3-043": {
    "o": "3.2",
    "c": "high"
  },
  "SEC-D3-044": {
    "o": "3.2",
    "c": "high"
  },
  "SEC-D3-045": {
    "o": "3.2",
    "c": "high"
  },
  "SEC-D3-046": {
    "o": "3.2",
    "c": "high"
  },
  "SEC-D3-047": {
    "o": "3.2",
    "c": "high"
  },
  "SEC-D3-048": {
    "o": "3.1",
    "c": "high"
  },
  "SEC-D3-049": {
    "o": "3.3",
    "c": "high"
  },
  "SEC-D3-050": {
    "o": "3.2",
    "c": "high"
  },
  "SEC-D3-051": {
    "o": "3.2",
    "c": "high"
  },
  "SEC-D3-052": {
    "o": "3.3",
    "c": "high"
  },
  "SEC-D3-053": {
    "o": "3.4",
    "c": "high"
  },
  "SEC-D3-054": {
    "o": "3.1",
    "c": "low"
  },
  "SEC-D3-055": {
    "o": "3.4",
    "c": "high"
  },
  "SEC-D3-056": {
    "o": "3.3",
    "c": "high"
  },
  "SEC-D3-057": {
    "o": "3.4",
    "c": "high"
  },
  "SEC-D3-058": {
    "o": "3.3",
    "c": "high"
  },
  "SEC-D3-059": {
    "o": "3.2",
    "c": "high"
  },
  "SEC-D3-060": {
    "o": "3.2",
    "c": "high"
  },
  "SEC-D3-061": {
    "o": "3.1",
    "c": "high"
  },
  "SEC-D3-062": {
    "o": "3.3",
    "c": "high"
  },
  "SEC-D3-063": {
    "o": "3.2",
    "c": "high"
  },
  "SEC-D3-064": {
    "o": "3.4",
    "c": "high"
  },
  "SEC-D3-065": {
    "o": "3.3",
    "c": "low"
  },
  "SEC-D3-066": {
    "o": "3.3",
    "c": "high"
  },
  "SEC-D3-067": {
    "o": "3.2",
    "c": "high"
  },
  "SEC-D3-068": {
    "o": "3.4",
    "c": "high"
  },
  "SEC-D3-069": {
    "o": "3.3",
    "c": "high"
  },
  "SEC-D3-070": {
    "o": "3.2",
    "c": "high"
  },
  "SEC-D3-071": {
    "o": "3.4",
    "c": "high"
  },
  "SEC-D3-072": {
    "o": "3.2",
    "c": "high"
  },
  "SEC-D3-073": {
    "o": "3.2",
    "c": "high"
  },
  "SEC-D3-074": {
    "o": "3.2",
    "c": "high"
  },
  "SEC-D3-075": {
    "o": "3.1",
    "c": "high"
  },
  "SEC-D3-076": {
    "o": "3.1",
    "c": "high"
  },
  "SEC-D3-077": {
    "o": "3.4",
    "c": "low"
  },
  "SEC-D3-078": {
    "o": "3.3",
    "c": "high"
  },
  "SEC-D3-079": {
    "o": "3.1",
    "c": "high"
  },
  "SEC-D3-080": {
    "o": "3.3",
    "c": "low"
  },
  "SEC-D3-081": {
    "o": "3.4",
    "c": "high"
  },
  "SEC-D3-082": {
    "o": "3.3",
    "c": "high"
  },
  "SEC-D3-083": {
    "o": "3.3",
    "c": "high"
  },
  "SEC-D3-084": {
    "o": "3.2",
    "c": "high"
  },
  "SEC-D3-085": {
    "o": "3.1",
    "c": "high"
  },
  "SEC-D3-086": {
    "o": "3.2",
    "c": "high"
  },
  "SEC-D3-087": {
    "o": "3.2",
    "c": "high"
  },
  "SEC-D3-088": {
    "o": "3.4",
    "c": "high"
  },
  "SEC-D3-089": {
    "o": "3.4",
    "c": "high"
  },
  "SEC-D3-090": {
    "o": "3.3",
    "c": "manual"
  },
  "SEC-D3-091": {
    "o": "3.4",
    "c": "low"
  },
  "SEC-D3-092": {
    "o": "3.4",
    "c": "high"
  },
  "SEC-D3-093": {
    "o": "3.3",
    "c": "high"
  },
  "SEC-D3-094": {
    "o": "3.4",
    "c": "high"
  },
  "SEC-D3-095": {
    "o": "3.4",
    "c": "high"
  },
  "SEC-D3-096": {
    "o": "3.3",
    "c": "high"
  },
  "SEC-D3-097": {
    "o": "3.3",
    "c": "high"
  },
  "SEC-D3-098": {
    "o": "3.1",
    "c": "high"
  },
  "SEC-D3-099": {
    "o": "3.2",
    "c": "high"
  },
  "SEC-D3-100": {
    "o": "3.1",
    "c": "high"
  },
  "SEC-D3-101": {
    "o": "3.1",
    "c": "high"
  },
  "SEC-D3-102": {
    "o": "3.4",
    "c": "high"
  },
  "SEC-D3-103": {
    "o": "3.4",
    "c": "high"
  },
  "SEC-D3-104": {
    "o": "3.4",
    "c": "high"
  },
  "SEC-D3-105": {
    "o": "3.1",
    "c": "high"
  },
  "SEC-D3-106": {
    "o": "3.2",
    "c": "high"
  },
  "SEC-D3-107": {
    "o": "3.4",
    "c": "high"
  },
  "SEC-D3-108": {
    "o": "3.3",
    "c": "high"
  },
  "SEC-D3-109": {
    "o": "3.3",
    "c": "high"
  },
  "SEC-D3-110": {
    "o": "3.4",
    "c": "high"
  },
  "SEC-D3-111": {
    "o": "3.1",
    "c": "high"
  },
  "SEC-D3-112": {
    "o": "3.2",
    "c": "high"
  },
  "SEC-D3-113": {
    "o": "3.2",
    "c": "high"
  },
  "SEC-D3-114": {
    "o": "3.3",
    "c": "high"
  },
  "SEC-D3-115": {
    "o": "3.2",
    "c": "high"
  },
  "SEC-D3-116": {
    "o": "3.2",
    "c": "high"
  },
  "SEC-D3-117": {
    "o": "3.3",
    "c": "high"
  },
  "SEC-D3-118": {
    "o": "3.1",
    "c": "high"
  },
  "SEC-D3-119": {
    "o": "3.1",
    "c": "high"
  },
  "SEC-D3-120": {
    "o": "3.2",
    "c": "high"
  },
  "SEC-D3-121": {
    "o": "3.4",
    "c": "high"
  },
  "SEC-D3-122": {
    "o": "3.2",
    "c": "high"
  },
  "SEC-D3-123": {
    "o": "3.4",
    "c": "high"
  },
  "SEC-D3-124": {
    "o": "3.3",
    "c": "high"
  },
  "SEC-D3-125": {
    "o": "3.3",
    "c": "high"
  },
  "SEC-D3-126": {
    "o": "3.4",
    "c": "high"
  },
  "SEC-D3-127": {
    "o": "3.2",
    "c": "high"
  },
  "SEC-D3-128": {
    "o": "3.2",
    "c": "high"
  },
  "SEC-D3-129": {
    "o": "3.2",
    "c": "high"
  },
  "SEC-D3-130": {
    "o": "3.2",
    "c": "high"
  },
  "SEC-D3-131": {
    "o": "3.1",
    "c": "high"
  },
  "SEC-D3-132": {
    "o": "3.3",
    "c": "high"
  },
  "SEC-D3-133": {
    "o": "3.2",
    "c": "high"
  },
  "SEC-D3-134": {
    "o": "3.2",
    "c": "high"
  },
  "SEC-D3-135": {
    "o": "3.1",
    "c": "low"
  },
  "SEC-D3-136": {
    "o": "3.1",
    "c": "high"
  },
  "SEC-D3-137": {
    "o": "3.3",
    "c": "high"
  },
  "SEC-D3-138": {
    "o": "3.1",
    "c": "high"
  },
  "SEC-D3-139": {
    "o": "3.2",
    "c": "high"
  },
  "SEC-D3-140": {
    "o": "3.2",
    "c": "high"
  },
  "SEC-D3-141": {
    "o": "3.1",
    "c": "manual"
  },
  "SEC-D3-142": {
    "o": "3.2",
    "c": "high"
  },
  "SEC-D3-143": {
    "o": "3.4",
    "c": "high"
  },
  "SEC-D3-144": {
    "o": "3.4",
    "c": "high"
  },
  "SEC-D3-145": {
    "o": "3.4",
    "c": "high"
  },
  "SEC-D3-146": {
    "o": "3.4",
    "c": "high"
  },
  "SEC-D3-147": {
    "o": "3.4",
    "c": "high"
  },
  "SEC-D3-148": {
    "o": "3.2",
    "c": "high"
  },
  "SEC-D3-149": {
    "o": "3.1",
    "c": "high"
  },
  "SEC-D3-150": {
    "o": "3.3",
    "c": "high"
  },
  "SEC-D3-151": {
    "o": "3.2",
    "c": "high"
  },
  "SEC-D3-152": {
    "o": "3.3",
    "c": "high"
  },
  "SEC-D3-153": {
    "o": "3.4",
    "c": "high"
  },
  "SEC-D3-154": {
    "o": "3.4",
    "c": "high"
  },
  "SEC-D3-155": {
    "o": "3.2",
    "c": "high"
  },
  "SEC-D3-156": {
    "o": "3.1",
    "c": "low"
  },
  "SEC-D3-157": {
    "o": "3.4",
    "c": "high"
  },
  "SEC-D3-158": {
    "o": "3.4",
    "c": "high"
  },
  "SEC-D3-159": {
    "o": "3.4",
    "c": "high"
  },
  "SEC-D3-160": {
    "o": "3.3",
    "c": "high"
  },
  "SEC-D3-161": {
    "o": "3.1",
    "c": "high"
  },
  "SEC-D3-162": {
    "o": "3.2",
    "c": "high"
  },
  "SEC-D3-163": {
    "o": "3.2",
    "c": "high"
  },
  "SEC-D3-164": {
    "o": "3.3",
    "c": "manual"
  },
  "SEC-D3-165": {
    "o": "3.3",
    "c": "high"
  },
  "SEC-D3-166": {
    "o": "3.1",
    "c": "high"
  },
  "SEC-D3-167": {
    "o": "3.1",
    "c": "high"
  },
  "SEC-D3-168": {
    "o": "3.1",
    "c": "high"
  },
  "SEC-D3-169": {
    "o": "3.2",
    "c": "high"
  },
  "SEC-D3-170": {
    "o": "3.4",
    "c": "low"
  },
  "SEC-D3-171": {
    "o": "3.1",
    "c": "high"
  },
  "SEC-D3-172": {
    "o": "3.4",
    "c": "high"
  },
  "SEC-D3-173": {
    "o": "3.1",
    "c": "manual"
  },
  "SEC-D3-174": {
    "o": "3.3",
    "c": "high"
  },
  "SEC-D3-175": {
    "o": "3.4",
    "c": "high"
  },
  "SEC-D3-176": {
    "o": "3.1",
    "c": "high"
  },
  "SEC-D3-177": {
    "o": "3.4",
    "c": "high"
  },
  "SEC-D3-178": {
    "o": "3.4",
    "c": "high"
  },
  "SEC-D3-179": {
    "o": "3.4",
    "c": "high"
  },
  "SEC-D3-180": {
    "o": "3.2",
    "c": "high"
  },
  "SEC-D3-181": {
    "o": "3.2",
    "c": "high"
  },
  "SEC-D3-182": {
    "o": "3.1",
    "c": "high"
  },
  "SEC-D3-183": {
    "o": "3.3",
    "c": "high"
  },
  "SEC-D3-184": {
    "o": "3.4",
    "c": "high"
  },
  "SEC-D3-185": {
    "o": "3.1",
    "c": "high"
  },
  "SEC-D3-186": {
    "o": "3.3",
    "c": "high"
  },
  "SEC-D3-187": {
    "o": "3.2",
    "c": "high"
  },
  "SEC-D3-188": {
    "o": "3.3",
    "c": "high"
  },
  "SEC-D3-189": {
    "o": "3.2",
    "c": "high"
  },
  "SEC-D3-190": {
    "o": "3.4",
    "c": "high"
  },
  "SEC-D3-191": {
    "o": "3.2",
    "c": "high"
  },
  "SEC-D3-192": {
    "o": "3.2",
    "c": "high"
  },
  "SEC-D3-193": {
    "o": "3.2",
    "c": "high"
  },
  "SEC-D3-194": {
    "o": "3.4",
    "c": "low"
  },
  "SEC-D3-195": {
    "o": "3.3",
    "c": "high"
  },
  "SEC-D3-196": {
    "o": "3.1",
    "c": "high"
  },
  "SEC-D3-197": {
    "o": "3.2",
    "c": "high"
  },
  "SEC-D3-198": {
    "o": "3.1",
    "c": "high"
  },
  "SEC-D3-199": {
    "o": "3.3",
    "c": "high"
  },
  "SEC-D3-200": {
    "o": "3.1",
    "c": "high"
  },
  "SEC-D3-201": {
    "o": "3.3",
    "c": "high"
  },
  "SEC-D3-202": {
    "o": "3.2",
    "c": "high"
  },
  "SEC-D3-203": {
    "o": "3.2",
    "c": "high"
  },
  "SEC-D3-204": {
    "o": "3.1",
    "c": "high"
  },
  "SEC-D3-205": {
    "o": "3.2",
    "c": "high"
  },
  "SEC-D3-206": {
    "o": "3.3",
    "c": "high"
  },
  "SEC-D3-207": {
    "o": "3.4",
    "c": "high"
  },
  "SEC-D3-208": {
    "o": "3.1",
    "c": "high"
  },
  "SEC-D3-209": {
    "o": "3.4",
    "c": "low"
  },
  "SEC-D3-210": {
    "o": "3.1",
    "c": "manual"
  },
  "SEC-D3-211": {
    "o": "3.1",
    "c": "high"
  },
  "SEC-D3-212": {
    "o": "3.4",
    "c": "high"
  },
  "SEC-D3-213": {
    "o": "3.3",
    "c": "high"
  },
  "SEC-D3-214": {
    "o": "3.2",
    "c": "low"
  },
  "SEC-D3-215": {
    "o": "3.2",
    "c": "high"
  },
  "SEC-D3-216": {
    "o": "3.1",
    "c": "high"
  },
  "SEC-D3-217": {
    "o": "3.1",
    "c": "high"
  },
  "SEC-D3-218": {
    "o": "3.2",
    "c": "high"
  },
  "SEC-D3-219": {
    "o": "3.1",
    "c": "high"
  },
  "SEC-D3-220": {
    "o": "3.1",
    "c": "high"
  },
  "SEC-D3-221": {
    "o": "3.3",
    "c": "high"
  },
  "SEC-D3-222": {
    "o": "3.2",
    "c": "high"
  },
  "SEC-D3-223": {
    "o": "3.1",
    "c": "high"
  },
  "SEC-D3-224": {
    "o": "3.2",
    "c": "high"
  },
  "SEC-D3-225": {
    "o": "3.2",
    "c": "high"
  },
  "SEC-D3-226": {
    "o": "3.2",
    "c": "high"
  },
  "SEC-D4-001": {
    "o": "4.1",
    "c": "high"
  },
  "SEC-D4-002": {
    "o": "4.8",
    "c": "high"
  },
  "SEC-D4-003": {
    "o": "4.5",
    "c": "low"
  },
  "SEC-D4-004": {
    "o": "4.5",
    "c": "high"
  },
  "SEC-D4-005": {
    "o": "4.5",
    "c": "high"
  },
  "SEC-D4-006": {
    "o": "4.3",
    "c": "high"
  },
  "SEC-D4-007": {
    "o": "4.3",
    "c": "high"
  },
  "SEC-D4-008": {
    "o": "4.5",
    "c": "high"
  },
  "SEC-D4-009": {
    "o": "4.3",
    "c": "high"
  },
  "SEC-D4-010": {
    "o": "4.3",
    "c": "high"
  },
  "SEC-D4-011": {
    "o": "4.3",
    "c": "low"
  },
  "SEC-D4-012": {
    "o": "4.3",
    "c": "high"
  },
  "SEC-D4-013": {
    "o": "4.3",
    "c": "high"
  },
  "SEC-D4-014": {
    "o": "4.1",
    "c": "low"
  },
  "SEC-D4-015": {
    "o": "4.3",
    "c": "high"
  },
  "SEC-D4-016": {
    "o": "4.3",
    "c": "high"
  },
  "SEC-D4-017": {
    "o": "4.3",
    "c": "high"
  },
  "SEC-D4-018": {
    "o": "4.3",
    "c": "high"
  },
  "SEC-D4-019": {
    "o": "4.1",
    "c": "low"
  },
  "SEC-D4-020": {
    "o": "4.5",
    "c": "high"
  },
  "SEC-D4-021": {
    "o": "4.1",
    "c": "high"
  },
  "SEC-D4-022": {
    "o": "4.3",
    "c": "high"
  },
  "SEC-D4-023": {
    "o": "4.6",
    "c": "high"
  },
  "SEC-D4-024": {
    "o": "4.3",
    "c": "low"
  },
  "SEC-D4-025": {
    "o": "4.6",
    "c": "high"
  },
  "SEC-D4-026": {
    "o": "4.4",
    "c": "high"
  },
  "SEC-D4-027": {
    "o": "4.1",
    "c": "low"
  },
  "SEC-D4-028": {
    "o": "4.6",
    "c": "high"
  },
  "SEC-D4-029": {
    "o": "4.1",
    "c": "high"
  },
  "SEC-D4-030": {
    "o": "4.1",
    "c": "high"
  },
  "SEC-D4-031": {
    "o": "4.1",
    "c": "high"
  },
  "SEC-D4-032": {
    "o": "4.1",
    "c": "high"
  },
  "SEC-D4-033": {
    "o": "4.1",
    "c": "high"
  },
  "SEC-D4-034": {
    "o": "4.1",
    "c": "high"
  },
  "SEC-D4-035": {
    "o": "4.1",
    "c": "high"
  },
  "SEC-D4-036": {
    "o": "4.1",
    "c": "high"
  },
  "SEC-D4-037": {
    "o": "4.1",
    "c": "high"
  },
  "SEC-D4-038": {
    "o": "4.8",
    "c": "low"
  },
  "SEC-D4-039": {
    "o": "4.6",
    "c": "high"
  },
  "SEC-D4-040": {
    "o": "4.5",
    "c": "high"
  },
  "SEC-D4-041": {
    "o": "4.1",
    "c": "high"
  },
  "SEC-D4-042": {
    "o": "4.1",
    "c": "low"
  },
  "SEC-D4-043": {
    "o": "4.1",
    "c": "high"
  },
  "SEC-D4-044": {
    "o": "4.4",
    "c": "high"
  },
  "SEC-D4-045": {
    "o": "4.5",
    "c": "low"
  },
  "SEC-D4-046": {
    "o": "4.6",
    "c": "high"
  },
  "SEC-D4-047": {
    "o": "4.6",
    "c": "high"
  },
  "SEC-D4-048": {
    "o": "4.6",
    "c": "high"
  },
  "SEC-D4-049": {
    "o": "4.6",
    "c": "high"
  },
  "SEC-D4-050": {
    "o": "4.6",
    "c": "high"
  },
  "SEC-D4-051": {
    "o": "4.6",
    "c": "high"
  },
  "SEC-D4-052": {
    "o": "4.6",
    "c": "high"
  },
  "SEC-D4-053": {
    "o": "4.1",
    "c": "low"
  },
  "SEC-D4-054": {
    "o": "4.6",
    "c": "high"
  },
  "SEC-D4-055": {
    "o": "4.6",
    "c": "high"
  },
  "SEC-D4-056": {
    "o": "4.5",
    "c": "high"
  },
  "SEC-D4-057": {
    "o": "4.6",
    "c": "high"
  },
  "SEC-D4-058": {
    "o": "4.3",
    "c": "low"
  },
  "SEC-D4-059": {
    "o": "4.6",
    "c": "high"
  },
  "SEC-D4-060": {
    "o": "4.8",
    "c": "high"
  },
  "SEC-D4-061": {
    "o": "4.8",
    "c": "low"
  },
  "SEC-D4-062": {
    "o": "4.3",
    "c": "high"
  },
  "SEC-D4-063": {
    "o": "4.3",
    "c": "low"
  },
  "SEC-D4-064": {
    "o": "4.9",
    "c": "manual"
  },
  "SEC-D4-065": {
    "o": "4.8",
    "c": "high"
  },
  "SEC-D4-066": {
    "o": "4.9",
    "c": "manual"
  },
  "SEC-D4-067": {
    "o": "4.4",
    "c": "high"
  },
  "SEC-D4-068": {
    "o": "4.8",
    "c": "high"
  },
  "SEC-D4-069": {
    "o": "4.3",
    "c": "low"
  },
  "SEC-D4-070": {
    "o": "4.3",
    "c": "low"
  },
  "SEC-D4-071": {
    "o": "4.1",
    "c": "low"
  },
  "SEC-D4-072": {
    "o": "4.9",
    "c": "low"
  },
  "SEC-D4-073": {
    "o": "4.8",
    "c": "manual"
  },
  "SEC-D4-074": {
    "o": "4.3",
    "c": "low"
  },
  "SEC-D4-075": {
    "o": "4.8",
    "c": "manual"
  },
  "SEC-D4-076": {
    "o": "4.8",
    "c": "high"
  },
  "SEC-D4-077": {
    "o": "4.4",
    "c": "low"
  },
  "SEC-D4-078": {
    "o": "4.1",
    "c": "high"
  },
  "SEC-D4-079": {
    "o": "4.8",
    "c": "manual"
  },
  "SEC-D4-080": {
    "o": "4.3",
    "c": "low"
  },
  "SEC-D4-081": {
    "o": "4.1",
    "c": "low"
  },
  "SEC-D4-082": {
    "o": "4.5",
    "c": "high"
  },
  "SEC-D4-083": {
    "o": "4.9",
    "c": "high"
  },
  "SEC-D4-084": {
    "o": "4.8",
    "c": "manual"
  },
  "SEC-D4-085": {
    "o": "4.2",
    "c": "manual"
  },
  "SEC-D4-086": {
    "o": "4.8",
    "c": "high"
  },
  "SEC-D4-087": {
    "o": "4.4",
    "c": "low"
  },
  "SEC-D4-088": {
    "o": "4.4",
    "c": "low"
  },
  "SEC-D4-089": {
    "o": "4.1",
    "c": "high"
  },
  "SEC-D4-090": {
    "o": "4.8",
    "c": "high"
  },
  "SEC-D4-091": {
    "o": "4.3",
    "c": "low"
  },
  "SEC-D4-092": {
    "o": "4.8",
    "c": "high"
  },
  "SEC-D4-093": {
    "o": "4.2",
    "c": "high"
  },
  "SEC-D4-094": {
    "o": "4.9",
    "c": "low"
  },
  "SEC-D4-095": {
    "o": "4.5",
    "c": "high"
  },
  "SEC-D4-096": {
    "o": "4.3",
    "c": "low"
  },
  "SEC-D4-097": {
    "o": "4.2",
    "c": "low"
  },
  "SEC-D4-098": {
    "o": "4.4",
    "c": "high"
  },
  "SEC-D4-099": {
    "o": "4.9",
    "c": "low"
  },
  "SEC-D4-100": {
    "o": "4.9",
    "c": "high"
  },
  "SEC-D4-101": {
    "o": "4.3",
    "c": "low"
  },
  "SEC-D4-102": {
    "o": "4.8",
    "c": "high"
  },
  "SEC-D4-103": {
    "o": "4.4",
    "c": "low"
  },
  "SEC-D4-104": {
    "o": "4.5",
    "c": "low"
  },
  "SEC-D4-105": {
    "o": "4.4",
    "c": "high"
  },
  "SEC-D4-106": {
    "o": "4.3",
    "c": "high"
  },
  "SEC-D4-107": {
    "o": "4.7",
    "c": "high"
  },
  "SEC-D4-108": {
    "o": "4.2",
    "c": "manual"
  },
  "SEC-D4-109": {
    "o": "4.7",
    "c": "high"
  },
  "SEC-D4-110": {
    "o": "4.3",
    "c": "low"
  },
  "SEC-D4-111": {
    "o": "4.5",
    "c": "high"
  },
  "SEC-D4-112": {
    "o": "4.4",
    "c": "low"
  },
  "SEC-D4-113": {
    "o": "4.5",
    "c": "high"
  },
  "SEC-D4-114": {
    "o": "4.8",
    "c": "high"
  },
  "SEC-D4-115": {
    "o": "4.8",
    "c": "high"
  },
  "SEC-D4-116": {
    "o": "4.1",
    "c": "high"
  },
  "SEC-D4-117": {
    "o": "4.1",
    "c": "high"
  },
  "SEC-D4-118": {
    "o": "4.3",
    "c": "high"
  },
  "SEC-D4-119": {
    "o": "4.4",
    "c": "high"
  },
  "SEC-D4-120": {
    "o": "4.5",
    "c": "low"
  },
  "SEC-D4-121": {
    "o": "4.6",
    "c": "low"
  },
  "SEC-D4-122": {
    "o": "4.6",
    "c": "low"
  },
  "SEC-D4-123": {
    "o": "4.7",
    "c": "high"
  },
  "SEC-D4-124": {
    "o": "4.8",
    "c": "high"
  },
  "SEC-D4-125": {
    "o": "4.8",
    "c": "high"
  },
  "SEC-D4-126": {
    "o": "4.8",
    "c": "high"
  },
  "SEC-D4-127": {
    "o": "4.6",
    "c": "high"
  },
  "SEC-D4-128": {
    "o": "4.6",
    "c": "high"
  },
  "SEC-D4-129": {
    "o": "4.6",
    "c": "high"
  },
  "SEC-D4-130": {
    "o": "4.1",
    "c": "low"
  },
  "SEC-D4-131": {
    "o": "4.1",
    "c": "high"
  },
  "SEC-D4-132": {
    "o": "4.1",
    "c": "high"
  },
  "SEC-D4-133": {
    "o": "4.1",
    "c": "high"
  },
  "SEC-D4-134": {
    "o": "4.9",
    "c": "low"
  },
  "SEC-D4-135": {
    "o": "4.3",
    "c": "high"
  },
  "SEC-D4-136": {
    "o": "4.3",
    "c": "high"
  },
  "SEC-D4-137": {
    "o": "4.8",
    "c": "high"
  },
  "SEC-D4-138": {
    "o": "4.3",
    "c": "high"
  },
  "SEC-D4-139": {
    "o": "4.4",
    "c": "high"
  },
  "SEC-D4-140": {
    "o": "4.1",
    "c": "high"
  },
  "SEC-D4-141": {
    "o": "4.6",
    "c": "high"
  },
  "SEC-D4-142": {
    "o": "4.1",
    "c": "high"
  },
  "SEC-D4-143": {
    "o": "4.5",
    "c": "high"
  },
  "SEC-D4-144": {
    "o": "4.3",
    "c": "high"
  },
  "SEC-D4-145": {
    "o": "4.6",
    "c": "high"
  },
  "SEC-D4-146": {
    "o": "4.3",
    "c": "high"
  },
  "SEC-D4-147": {
    "o": "4.3",
    "c": "low"
  },
  "SEC-D4-148": {
    "o": "4.5",
    "c": "high"
  },
  "SEC-D4-149": {
    "o": "4.1",
    "c": "high"
  },
  "SEC-D4-150": {
    "o": "4.1",
    "c": "high"
  },
  "SEC-D4-151": {
    "o": "4.3",
    "c": "high"
  },
  "SEC-D4-152": {
    "o": "4.5",
    "c": "high"
  },
  "SEC-D4-153": {
    "o": "4.4",
    "c": "high"
  },
  "SEC-D4-154": {
    "o": "4.1",
    "c": "low"
  },
  "SEC-D4-155": {
    "o": "4.3",
    "c": "manual"
  },
  "SEC-D4-156": {
    "o": "4.8",
    "c": "high"
  },
  "SEC-D4-157": {
    "o": "4.3",
    "c": "low"
  },
  "SEC-D4-158": {
    "o": "4.6",
    "c": "high"
  },
  "SEC-D4-159": {
    "o": "4.8",
    "c": "low"
  },
  "SEC-D4-160": {
    "o": "4.1",
    "c": "low"
  },
  "SEC-D4-161": {
    "o": "4.6",
    "c": "high"
  },
  "SEC-D4-162": {
    "o": "4.6",
    "c": "low"
  },
  "SEC-D4-163": {
    "o": "4.3",
    "c": "high"
  },
  "SEC-D4-164": {
    "o": "4.1",
    "c": "high"
  },
  "SEC-D4-165": {
    "o": "4.1",
    "c": "high"
  },
  "SEC-D4-166": {
    "o": "4.3",
    "c": "high"
  },
  "SEC-D4-167": {
    "o": "4.6",
    "c": "high"
  },
  "SEC-D4-168": {
    "o": "4.1",
    "c": "low"
  },
  "SEC-D4-169": {
    "o": "4.6",
    "c": "high"
  },
  "SEC-D4-170": {
    "o": "4.2",
    "c": "high"
  },
  "SEC-D4-171": {
    "o": "4.6",
    "c": "high"
  },
  "SEC-D4-172": {
    "o": "4.2",
    "c": "low"
  },
  "SEC-D4-173": {
    "o": "4.1",
    "c": "low"
  },
  "SEC-D4-174": {
    "o": "4.6",
    "c": "high"
  },
  "SEC-D4-175": {
    "o": "4.3",
    "c": "high"
  },
  "SEC-D4-176": {
    "o": "4.2",
    "c": "high"
  },
  "SEC-D4-177": {
    "o": "4.1",
    "c": "high"
  },
  "SEC-D4-178": {
    "o": "4.1",
    "c": "high"
  },
  "SEC-D4-179": {
    "o": "4.1",
    "c": "high"
  },
  "SEC-D4-180": {
    "o": "4.4",
    "c": "high"
  },
  "SEC-D4-181": {
    "o": "4.5",
    "c": "high"
  },
  "SEC-D4-182": {
    "o": "4.5",
    "c": "high"
  },
  "SEC-D4-183": {
    "o": "4.5",
    "c": "high"
  },
  "SEC-D4-184": {
    "o": "4.5",
    "c": "low"
  },
  "SEC-D4-185": {
    "o": "4.6",
    "c": "high"
  },
  "SEC-D4-186": {
    "o": "4.1",
    "c": "high"
  },
  "SEC-D4-187": {
    "o": "4.8",
    "c": "high"
  },
  "SEC-D4-188": {
    "o": "4.5",
    "c": "high"
  },
  "SEC-D4-189": {
    "o": "4.9",
    "c": "low"
  },
  "SEC-D4-190": {
    "o": "4.3",
    "c": "high"
  },
  "SEC-D4-191": {
    "o": "4.5",
    "c": "high"
  },
  "SEC-D4-192": {
    "o": "4.5",
    "c": "low"
  },
  "SEC-D4-193": {
    "o": "4.3",
    "c": "high"
  },
  "SEC-D4-194": {
    "o": "4.5",
    "c": "high"
  },
  "SEC-D4-195": {
    "o": "4.3",
    "c": "manual"
  },
  "SEC-D4-196": {
    "o": "4.2",
    "c": "high"
  },
  "SEC-D4-197": {
    "o": "4.6",
    "c": "high"
  },
  "SEC-D4-198": {
    "o": "4.5",
    "c": "high"
  },
  "SEC-D4-199": {
    "o": "4.5",
    "c": "manual"
  },
  "SEC-D4-200": {
    "o": "4.5",
    "c": "high"
  },
  "SEC-D4-201": {
    "o": "4.6",
    "c": "high"
  },
  "SEC-D4-202": {
    "o": "4.3",
    "c": "low"
  },
  "SEC-D4-203": {
    "o": "4.7",
    "c": "high"
  },
  "SEC-D4-204": {
    "o": "4.3",
    "c": "low"
  },
  "SEC-D4-205": {
    "o": "4.8",
    "c": "high"
  },
  "SEC-D4-206": {
    "o": "4.2",
    "c": "high"
  },
  "SEC-D4-207": {
    "o": "4.3",
    "c": "high"
  },
  "SEC-D4-208": {
    "o": "4.6",
    "c": "high"
  },
  "SEC-D4-209": {
    "o": "4.3",
    "c": "high"
  },
  "SEC-D4-210": {
    "o": "4.2",
    "c": "manual"
  },
  "SEC-D4-211": {
    "o": "4.6",
    "c": "high"
  },
  "SEC-D4-212": {
    "o": "4.9",
    "c": "high"
  },
  "SEC-D4-213": {
    "o": "4.1",
    "c": "high"
  },
  "SEC-D4-214": {
    "o": "4.1",
    "c": "high"
  },
  "SEC-D4-215": {
    "o": "4.6",
    "c": "high"
  },
  "SEC-D5-001": {
    "o": "5.4",
    "c": "manual"
  },
  "SEC-D5-002": {
    "o": "5.2",
    "c": "high"
  },
  "SEC-D5-003": {
    "o": "5.2",
    "c": "high"
  },
  "SEC-D5-004": {
    "o": "5.1",
    "c": "high"
  },
  "SEC-D5-005": {
    "o": "5.5",
    "c": "high"
  },
  "SEC-D5-006": {
    "o": "5.1",
    "c": "low"
  },
  "SEC-D5-007": {
    "o": "5.1",
    "c": "high"
  },
  "SEC-D5-008": {
    "o": "5.2",
    "c": "high"
  },
  "SEC-D5-009": {
    "o": "5.2",
    "c": "high"
  },
  "SEC-D5-010": {
    "o": "5.1",
    "c": "high"
  },
  "SEC-D5-011": {
    "o": "5.2",
    "c": "high"
  },
  "SEC-D5-012": {
    "o": "5.1",
    "c": "high"
  },
  "SEC-D5-013": {
    "o": "5.1",
    "c": "high"
  },
  "SEC-D5-014": {
    "o": "5.2",
    "c": "high"
  },
  "SEC-D5-015": {
    "o": "5.1",
    "c": "high"
  },
  "SEC-D5-016": {
    "o": "5.5",
    "c": "high"
  },
  "SEC-D5-017": {
    "o": "5.1",
    "c": "high"
  },
  "SEC-D5-018": {
    "o": "5.2",
    "c": "high"
  },
  "SEC-D5-019": {
    "o": "5.1",
    "c": "high"
  },
  "SEC-D5-020": {
    "o": "5.2",
    "c": "high"
  },
  "SEC-D5-021": {
    "o": "5.1",
    "c": "high"
  },
  "SEC-D5-022": {
    "o": "5.2",
    "c": "high"
  },
  "SEC-D5-023": {
    "o": "5.1",
    "c": "low"
  },
  "SEC-D5-024": {
    "o": "5.1",
    "c": "high"
  },
  "SEC-D5-025": {
    "o": "5.4",
    "c": "high"
  },
  "SEC-D5-026": {
    "o": "5.2",
    "c": "high"
  },
  "SEC-D5-027": {
    "o": "5.1",
    "c": "high"
  },
  "SEC-D5-028": {
    "o": "5.1",
    "c": "low"
  },
  "SEC-D5-029": {
    "o": "5.2",
    "c": "high"
  },
  "SEC-D5-030": {
    "o": "5.1",
    "c": "high"
  },
  "SEC-D5-031": {
    "o": "5.3",
    "c": "high"
  },
  "SEC-D5-032": {
    "o": "5.1",
    "c": "high"
  },
  "SEC-D5-033": {
    "o": "5.1",
    "c": "manual"
  },
  "SEC-D5-034": {
    "o": "5.1",
    "c": "high"
  },
  "SEC-D5-035": {
    "o": "5.1",
    "c": "high"
  },
  "SEC-D5-036": {
    "o": "5.2",
    "c": "high"
  },
  "SEC-D5-037": {
    "o": "5.6",
    "c": "low"
  },
  "SEC-D5-038": {
    "o": "5.3",
    "c": "high"
  },
  "SEC-D5-039": {
    "o": "5.2",
    "c": "high"
  },
  "SEC-D5-040": {
    "o": "5.5",
    "c": "high"
  },
  "SEC-D5-041": {
    "o": "5.1",
    "c": "high"
  },
  "SEC-D5-042": {
    "o": "5.1",
    "c": "low"
  },
  "SEC-D5-043": {
    "o": "5.2",
    "c": "high"
  },
  "SEC-D5-044": {
    "o": "5.1",
    "c": "low"
  },
  "SEC-D5-045": {
    "o": "5.2",
    "c": "high"
  },
  "SEC-D5-046": {
    "o": "5.1",
    "c": "high"
  },
  "SEC-D5-047": {
    "o": "5.4",
    "c": "high"
  },
  "SEC-D5-048": {
    "o": "5.1",
    "c": "high"
  },
  "SEC-D5-049": {
    "o": "5.3",
    "c": "manual"
  },
  "SEC-D5-050": {
    "o": "5.1",
    "c": "high"
  },
  "SEC-D5-051": {
    "o": "5.4",
    "c": "high"
  },
  "SEC-D5-052": {
    "o": "5.2",
    "c": "high"
  },
  "SEC-D5-053": {
    "o": "5.1",
    "c": "low"
  },
  "SEC-D5-054": {
    "o": "5.2",
    "c": "high"
  },
  "SEC-D5-055": {
    "o": "5.5",
    "c": "high"
  },
  "SEC-D5-056": {
    "o": "5.3",
    "c": "high"
  },
  "SEC-D5-057": {
    "o": "5.5",
    "c": "high"
  },
  "SEC-D5-058": {
    "o": "5.2",
    "c": "manual"
  },
  "SEC-D5-059": {
    "o": "5.5",
    "c": "high"
  },
  "SEC-D5-060": {
    "o": "5.2",
    "c": "high"
  },
  "SEC-D5-061": {
    "o": "5.2",
    "c": "high"
  },
  "SEC-D5-062": {
    "o": "5.5",
    "c": "high"
  },
  "SEC-D5-063": {
    "o": "5.2",
    "c": "high"
  },
  "SEC-D5-064": {
    "o": "5.5",
    "c": "high"
  },
  "SEC-D5-065": {
    "o": "5.4",
    "c": "high"
  },
  "SEC-D5-066": {
    "o": "5.2",
    "c": "high"
  },
  "SEC-D5-067": {
    "o": "5.5",
    "c": "high"
  },
  "SEC-D5-068": {
    "o": "5.5",
    "c": "high"
  },
  "SEC-D5-069": {
    "o": "5.5",
    "c": "high"
  },
  "SEC-D5-070": {
    "o": "5.5",
    "c": "high"
  },
  "SEC-D5-071": {
    "o": "5.2",
    "c": "low"
  },
  "SEC-D5-072": {
    "o": "5.2",
    "c": "high"
  },
  "SEC-D5-073": {
    "o": "5.5",
    "c": "high"
  },
  "SEC-D5-074": {
    "o": "5.5",
    "c": "high"
  },
  "SEC-D5-075": {
    "o": "5.5",
    "c": "high"
  },
  "SEC-D5-076": {
    "o": "5.5",
    "c": "high"
  },
  "SEC-D5-077": {
    "o": "5.4",
    "c": "low"
  },
  "SEC-D5-078": {
    "o": "5.5",
    "c": "low"
  },
  "SEC-D5-079": {
    "o": "5.5",
    "c": "high"
  },
  "SEC-D5-080": {
    "o": "5.2",
    "c": "high"
  },
  "SEC-D5-081": {
    "o": "5.5",
    "c": "high"
  },
  "SEC-D5-082": {
    "o": "5.2",
    "c": "high"
  },
  "SEC-D5-083": {
    "o": "5.5",
    "c": "high"
  },
  "SEC-D5-084": {
    "o": "5.1",
    "c": "high"
  },
  "SEC-D5-085": {
    "o": "5.1",
    "c": "low"
  },
  "SEC-D5-086": {
    "o": "5.1",
    "c": "high"
  },
  "SEC-D5-087": {
    "o": "5.1",
    "c": "high"
  },
  "SEC-D5-088": {
    "o": "5.4",
    "c": "high"
  },
  "SEC-D5-089": {
    "o": "5.2",
    "c": "manual"
  },
  "SEC-D5-090": {
    "o": "5.2",
    "c": "high"
  },
  "SEC-D5-091": {
    "o": "5.3",
    "c": "low"
  },
  "SEC-D5-092": {
    "o": "5.3",
    "c": "high"
  },
  "SEC-D5-093": {
    "o": "5.2",
    "c": "high"
  },
  "SEC-D5-094": {
    "o": "5.1",
    "c": "high"
  },
  "SEC-D5-095": {
    "o": "5.4",
    "c": "high"
  },
  "SEC-D5-096": {
    "o": "5.3",
    "c": "high"
  },
  "SEC-D5-097": {
    "o": "5.2",
    "c": "high"
  },
  "SEC-D5-098": {
    "o": "5.2",
    "c": "high"
  },
  "SEC-D5-099": {
    "o": "5.2",
    "c": "high"
  },
  "SEC-D5-100": {
    "o": "5.6",
    "c": "high"
  },
  "SEC-D5-101": {
    "o": "5.2",
    "c": "high"
  },
  "SEC-D5-102": {
    "o": "5.2",
    "c": "high"
  },
  "SEC-D5-103": {
    "o": "5.3",
    "c": "high"
  },
  "SEC-D5-104": {
    "o": "5.2",
    "c": "high"
  },
  "SEC-D5-105": {
    "o": "5.2",
    "c": "high"
  },
  "SEC-D5-106": {
    "o": "5.2",
    "c": "high"
  },
  "SEC-D5-107": {
    "o": "5.2",
    "c": "high"
  },
  "SEC-D5-108": {
    "o": "5.2",
    "c": "high"
  },
  "SEC-D5-109": {
    "o": "5.2",
    "c": "high"
  },
  "SEC-D5-110": {
    "o": "5.2",
    "c": "high"
  },
  "SEC-D5-111": {
    "o": "5.3",
    "c": "low"
  },
  "SEC-D5-112": {
    "o": "5.2",
    "c": "high"
  },
  "SEC-D5-113": {
    "o": "5.2",
    "c": "high"
  },
  "SEC-D5-114": {
    "o": "5.1",
    "c": "low"
  },
  "SEC-D5-115": {
    "o": "5.4",
    "c": "high"
  },
  "SEC-D5-116": {
    "o": "5.2",
    "c": "high"
  },
  "SEC-D5-117": {
    "o": "5.2",
    "c": "manual"
  },
  "SEC-D5-118": {
    "o": "5.2",
    "c": "high"
  },
  "SEC-D5-119": {
    "o": "5.5",
    "c": "high"
  },
  "SEC-D5-120": {
    "o": "5.1",
    "c": "high"
  },
  "SEC-D5-121": {
    "o": "5.5",
    "c": "high"
  },
  "SEC-D5-122": {
    "o": "5.5",
    "c": "high"
  },
  "SEC-D5-123": {
    "o": "5.1",
    "c": "high"
  },
  "SEC-D5-124": {
    "o": "5.2",
    "c": "low"
  },
  "SEC-D5-125": {
    "o": "5.1",
    "c": "high"
  },
  "SEC-D5-126": {
    "o": "5.3",
    "c": "high"
  },
  "SEC-D5-127": {
    "o": "5.1",
    "c": "high"
  },
  "SEC-D5-128": {
    "o": "5.4",
    "c": "low"
  },
  "SEC-D5-129": {
    "o": "5.1",
    "c": "high"
  },
  "SEC-D5-130": {
    "o": "5.1",
    "c": "high"
  },
  "SEC-D5-131": {
    "o": "5.4",
    "c": "high"
  },
  "SEC-D5-132": {
    "o": "5.2",
    "c": "high"
  },
  "SEC-D5-133": {
    "o": "5.3",
    "c": "high"
  },
  "SEC-D5-134": {
    "o": "5.2",
    "c": "high"
  },
  "SEC-D5-135": {
    "o": "5.2",
    "c": "high"
  },
  "SEC-D5-136": {
    "o": "5.1",
    "c": "high"
  },
  "SEC-D5-137": {
    "o": "5.2",
    "c": "high"
  },
  "SEC-D5-138": {
    "o": "5.3",
    "c": "high"
  },
  "SEC-D5-139": {
    "o": "5.3",
    "c": "high"
  },
  "SEC-D5-140": {
    "o": "5.2",
    "c": "high"
  },
  "SEC-D5-141": {
    "o": "5.3",
    "c": "low"
  },
  "SEC-D5-142": {
    "o": "5.2",
    "c": "high"
  },
  "SEC-D5-143": {
    "o": "5.2",
    "c": "high"
  },
  "SEC-D5-144": {
    "o": "5.2",
    "c": "high"
  },
  "SEC-D5-145": {
    "o": "5.2",
    "c": "high"
  },
  "SEC-D5-146": {
    "o": "5.2",
    "c": "low"
  },
  "SEC-D5-147": {
    "o": "5.1",
    "c": "low"
  },
  "SEC-D5-148": {
    "o": "5.2",
    "c": "high"
  },
  "SEC-D5-149": {
    "o": "5.2",
    "c": "high"
  },
  "SEC-D5-150": {
    "o": "5.1",
    "c": "high"
  },
  "SEC-D5-151": {
    "o": "5.1",
    "c": "low"
  },
  "SEC-D5-152": {
    "o": "5.1",
    "c": "manual"
  },
  "SEC-D5-153": {
    "o": "5.2",
    "c": "high"
  },
  "SEC-D5-154": {
    "o": "5.2",
    "c": "high"
  },
  "SEC-D5-155": {
    "o": "5.6",
    "c": "low"
  },
  "SEC-D5-156": {
    "o": "5.4",
    "c": "low"
  },
  "SEC-D5-157": {
    "o": "5.1",
    "c": "high"
  },
  "SEC-D5-158": {
    "o": "5.3",
    "c": "manual"
  },
  "SEC-D5-159": {
    "o": "5.2",
    "c": "manual"
  },
  "SEC-D5-160": {
    "o": "5.2",
    "c": "high"
  },
  "SEC-D5-161": {
    "o": "5.1",
    "c": "high"
  },
  "SEC-D5-162": {
    "o": "5.4",
    "c": "high"
  },
  "SEC-D5-163": {
    "o": "5.4",
    "c": "high"
  },
  "SEC-D5-164": {
    "o": "5.3",
    "c": "high"
  },
  "SEC-D5-165": {
    "o": "5.2",
    "c": "high"
  },
  "SEC-D5-166": {
    "o": "5.2",
    "c": "high"
  },
  "SEC-D5-167": {
    "o": "5.2",
    "c": "high"
  },
  "SEC-D5-168": {
    "o": "5.2",
    "c": "low"
  },
  "SEC-D5-169": {
    "o": "5.2",
    "c": "manual"
  },
  "SEC-D5-170": {
    "o": "5.5",
    "c": "high"
  },
  "SEC-D5-171": {
    "o": "5.3",
    "c": "high"
  },
  "SEC-D5-172": {
    "o": "5.2",
    "c": "high"
  },
  "SEC-D5-173": {
    "o": "5.2",
    "c": "high"
  },
  "SEC-D5-174": {
    "o": "5.1",
    "c": "high"
  },
  "SEC-D5-175": {
    "o": "5.1",
    "c": "high"
  },
  "SEC-D5-176": {
    "o": "5.2",
    "c": "low"
  },
  "SEC-D5-177": {
    "o": "5.1",
    "c": "low"
  },
  "SEC-D5-178": {
    "o": "5.1",
    "c": "high"
  },
  "SEC-D5-179": {
    "o": "5.2",
    "c": "high"
  },
  "SEC-D5-180": {
    "o": "5.5",
    "c": "high"
  },
  "SEC-D5-181": {
    "o": "5.3",
    "c": "low"
  },
  "SEC-D5-182": {
    "o": "5.6",
    "c": "high"
  },
  "SEC-D5-183": {
    "o": "5.6",
    "c": "high"
  },
  "SEC-D5-184": {
    "o": "5.4",
    "c": "high"
  },
  "SEC-D5-185": {
    "o": "5.3",
    "c": "high"
  },
  "SEC-D5-186": {
    "o": "5.1",
    "c": "high"
  },
  "SEC-D5-187": {
    "o": "5.1",
    "c": "high"
  },
  "SEC-D5-188": {
    "o": "5.3",
    "c": "high"
  },
  "SEC-D5-189": {
    "o": "5.6",
    "c": "high"
  },
  "SEC-D5-190": {
    "o": "5.6",
    "c": "high"
  },
  "SEC-D5-191": {
    "o": "5.5",
    "c": "low"
  },
  "SEC-D5-192": {
    "o": "5.1",
    "c": "low"
  },
  "SEC-D5-193": {
    "o": "5.1",
    "c": "high"
  },
  "SEC-D5-194": {
    "o": "5.1",
    "c": "high"
  },
  "SEC-D5-195": {
    "o": "5.6",
    "c": "low"
  },
  "SEC-D5-196": {
    "o": "5.3",
    "c": "high"
  },
  "SEC-D5-197": {
    "o": "5.3",
    "c": "low"
  },
  "SEC-D5-198": {
    "o": "5.4",
    "c": "high"
  },
  "SEC-D5-199": {
    "o": "5.4",
    "c": "high"
  },
  "SEC-D5-200": {
    "o": "5.6",
    "c": "high"
  },
  "SEC-D5-201": {
    "o": "5.6",
    "c": "low"
  },
  "SEC-D5-202": {
    "o": "5.6",
    "c": "high"
  },
  "SEC-D5-203": {
    "o": "5.3",
    "c": "high"
  },
  "SEC-D5-204": {
    "o": "5.6",
    "c": "high"
  },
  "SEC-D5-205": {
    "o": "5.1",
    "c": "high"
  },
  "SEC-D5-206": {
    "o": "5.1",
    "c": "high"
  },
  "SEC-D5-207": {
    "o": "5.4",
    "c": "high"
  },
  "SEC-D5-208": {
    "o": "5.3",
    "c": "high"
  },
  "SEC-D5-209": {
    "o": "5.2",
    "c": "high"
  },
  "SEC-D5-210": {
    "o": "5.5",
    "c": "high"
  },
  "SEC-D5-211": {
    "o": "5.1",
    "c": "high"
  },
  "SEC-D5-212": {
    "o": "5.1",
    "c": "low"
  },
  "SEC-D5-213": {
    "o": "5.6",
    "c": "high"
  },
  "SEC-D5-214": {
    "o": "5.4",
    "c": "high"
  },
  "SEC-D5-215": {
    "o": "5.5",
    "c": "high"
  },
  "SEC-D5-216": {
    "o": "5.1",
    "c": "high"
  },
  "SEC-D5-217": {
    "o": "5.6",
    "c": "high"
  },
  "SEC-D5-218": {
    "o": "5.6",
    "c": "high"
  },
  "SEC-D5-219": {
    "o": "5.6",
    "c": "high"
  },
  "SEC-D5-220": {
    "o": "5.6",
    "c": "high"
  },
  "SEC-D5-221": {
    "o": "5.6",
    "c": "manual"
  },
  "SEC-D5-222": {
    "o": "5.2",
    "c": "low"
  },
  "SEC-D5-223": {
    "o": "5.6",
    "c": "high"
  },
  "SEC-D5-224": {
    "o": "5.4",
    "c": "high"
  },
  "SEC-D5-225": {
    "o": "5.1",
    "c": "low"
  },
  "SEC-D5-226": {
    "o": "5.2",
    "c": "high"
  },
  "SEC-D5-227": {
    "o": "5.1",
    "c": "high"
  }
};
