#!/usr/bin/env python3
"""Tag every question in questions/domain<N>.js with a SY0-701 objective (1.1 - 5.6).

Usage (from the QUIZ folder):
    python tools/classify_objectives.py            # all five domains
    python tools/classify_objectives.py 2          # one domain, for a pilot

Writes:
    questions/objectives.js         window.QUESTION_OBJECTIVES + window.OBJECTIVE_META
    tools/objective-review.md       what landed where, and what needs a human

Why a separate file
-------------------
questions/domain<N>.js is GENERATED by extract_domain.py. Tags written into
those files would vanish on the next re-run, so they live in their own file
keyed by question id. Re-running the extractor cannot lose them, and a question
that disappears from a bank simply stops being looked up.

How the tagging works
---------------------
The objectives document lists, for every objective, the exact terms CompTIA
expects ("Honeytoken", "Annualized loss expectancy (ALE)", ...). Those term
trees are the classifier: a question is scored against the objectives OF ITS OWN
DOMAIN by how many of their terms it uses. Knowing the domain already is what
makes this accurate - the choice is between 4 and 9 objectives, never 28.

Three things keep it honest:

1. Generic terms are down-weighted. "Encryption" appears under 1.4, 2.5, 3.3
   and 5.1; "Honeytoken" appears once. Weight is inverse to how many objectives
   in the domain use the term, so distinctive terms decide the match.
2. Longer terms outrank shorter ones. Matching "business impact analysis" is
   stronger evidence than matching "impact".
3. The stem and answers count double the explanation. The explanation often
   discusses the distractors, which belong to other objectives.

A question is tagged "high" confidence only when it has a clear winner. Anything
close, or with little evidence either way, is tagged "review" and listed in the
report rather than filed silently in the wrong cluster.
"""
import json
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path

QUIZ_DIR = Path(__file__).resolve().parent.parent
OBJECTIVES_MD = QUIZ_DIR.parent / "SECURITY_PLUS_SY0-701_EXAM_OBJECTIVES_AI.md"

# Terms this short or this generic are ignored unless they arrive as an acronym.
STOP_TERMS = {
    "internal", "external", "other considerations", "considerations", "tools",
    "activities", "process", "types", "levels", "level", "factors", "benefits",
    "implementations", "children", "term", "scope", "development", "execution",
    "identification methods", "analysis", "reporting", "testing", "training",
    "monitoring and revision", "standards", "procedures", "policies",
    "guidelines", "questionnaires", "attestation", "power", "compute", "cost",
    "war", "ethical", "revenge", "hot", "cold", "warm", "recovery", "impact",
    "probability", "likelihood", "frequency", "encryption", "hashing",
    "segmentation", "patching", "monitoring", "isolation", "permissions",
    "availability", "resilience", "scalability", "sensors", "inventory",
    # Bare generic nouns. Each of these won a match on its own during the first
    # pass and filed a question in the wrong objective: "System" put a secure-
    # enclave question under AAA, "access" and "Infrastructure" pulled site and
    # backup questions away from resilience.
    "system", "systems", "access", "application", "applications",
    "infrastructure", "technology", "people", "verification", "audit",
    "insurance", "ownership", "classification", "prioritize", "confirmation",
}


# --- alias table ----------------------------------------------------------
# The objectives name concepts ("Authentication protocols"); the book asks about
# products and protocols ("Kerberos", "TACACS+"). Without these, a question can
# use precise vocabulary and still score zero. Each entry is a term the exam
# document does not spell out, mapped to the objective it belongs under.
# Keep one line per term with the reason implicit in the grouping.
ALIASES = {
    # 1.2 -- AAA, authentication and authorization models
    "1.2": ["Kerberos", "OpenID", "ticket-granting", "TGT", "RADIUS", "TACACS+",
            "802.1X", "EAP", "single sign-on", "SSO", "accounting records",
            "identity provider", "IdP", "service provider", "SP"],
    # 1.4 -- cryptography: the algorithms and artefacts behind the concepts
    "1.4": ["AES", "RSA", "ECC", "elliptic curve", "Diffie-Hellman", "DES",
            "3DES", "Blowfish", "Twofish", "ChaCha", "SHA-1", "SHA-2", "SHA-256",
            "SHA", "MD5", "HMAC", "bcrypt", "PBKDF2", "scrypt", "GPG", "PGP",
            "X.509", "certificate signing request", "wildcard certificate",
            "cipher", "ciphertext", "plaintext", "nonce", "initialization vector",
            "perfect forward secrecy", "ephemeral key"],
    # 2.4 -- named malware and attack families
    "2.4": ["botnet", "command and control", "C2", "beaconing", "exfiltration",
            "SQL injection", "XSS", "CSRF", "cross-site request forgery",
            "pass-the-hash", "golden ticket", "rainbow table", "dictionary attack",
            "ARP poisoning", "DNS poisoning", "typo", "smurf", "SYN flood"],
    # 3.2 -- appliances and secure communications
    "3.2": ["DMZ", "screened subnet", "bastion", "reverse proxy", "WAF",
            "next-generation firewall", "stateful", "stateless", "ACL rule",
            "site-to-site", "always-on VPN", "split tunnel", "full tunnel",
            "L2TP", "IKE", "GRE"],
    # 4.1 -- hardening and endpoint techniques
    "4.1": ["group policy object", "GPO", "CIS benchmark", "STIG", "baseline image",
            "golden image", "TPM attestation", "secure boot", "UEFI",
            "application allow list", "AppLocker"],
    # 4.3 -- vulnerability management tooling
    "4.3": ["Nessus", "OpenVAS", "Qualys", "nmap", "CVSS score", "CVE-",
            "false positive", "false negative", "credentialed scan",
            "uncredentialed scan", "agent-based scan"],
    # 4.4 -- monitoring and the tools that produce the telemetry
    "4.4": ["Splunk", "syslog", "log aggregation", "SIEM", "NetFlow", "SNMP",
            "correlation rule", "alert fatigue", "Wireshark", "tcpdump"],
    # 4.6 -- identity and access management in practice
    "4.6": ["TOTP", "HOTP", "authenticator app", "push notification", "FIDO",
            "U2F", "YubiKey", "smart card", "CAC", "PIV", "SAML assertion",
            "OAuth token", "LDAP", "Active Directory", "sudo", "su ",
            "service account", "just-in-time", "PAM"],
    # 4.8 / 4.9 -- incident response and investigation
    "4.8": ["playbook execution", "eradication", "containment", "chain of custody",
            "forensic image", "write blocker", "order of volatility", "legal hold"],
    "4.9": ["packet capture", "pcap", "log review", "dashboard", "SIEM query",
            "endpoint log", "firewall log", "netflow record"],
    # 5.2 -- quantitative risk
    "5.2": ["SLE", "ALE", "ARO", "exposure factor", "asset value", "risk matrix",
            "heat map", "risk register", "RTO", "RPO", "MTTR", "MTBF"],
    # 5.3 -- vendor agreements
    "5.3": ["SLA", "MOU", "MOA", "MSA", "NDA", "BPA", "statement of work",
            "right-to-audit", "due diligence"],
    # 5.4 -- privacy and compliance regimes
    "5.4": ["GDPR", "HIPAA", "PCI DSS", "SOX", "CCPA", "FERPA", "GLBA",
            "data subject", "right to be forgotten", "data retention"],
    # 5.5 -- audits and penetration testing
    "5.5": ["red team", "blue team", "purple team", "white box", "black box",
            "gray box", "rules of engagement", "bug bounty", "SOC 2", "ISO 27001"],
    # --- second pass: written after reading the unsorted list, so each entry
    # --- answers a question that scored zero or tied on a generic word.
    "2.2": ["open port", "open service port", "instant messaging", "Discord",
            "Slack", "messaging platform", "attack surface", "removable media",
            "USB drive", "default credential", "unsupported system",
            "end-of-life software"],
    "2.4": ["missing logs", "audit.log", "logs were cleared", "log deletion",
            "concurrent session", "impossible travel", "account lockout",
            "out-of-cycle", "beacon", "indicator of compromise"],
    "2.5": ["disabling unnecessary", "unnecessary service", "unnecessary port",
            "host-based firewall", "endpoint protection", "MDM", "Intune",
            "Jamf", "configuration enforcement", "sanitization", "degaussing",
            "shredding", "allow list", "deny list", "harden"],
    "3.1": ["container", "containers", "containerized", "Docker", "Kubernetes",
            "decentralized", "centralized", "microservice", "serverless",
            "air gap", "air-gapped", "infrastructure as code", "IaC",
            "hypervisor", "elasticity", "auto-scaling", "IoT device",
            "firmware update", "embedded device", "responsibility matrix"],
    "3.2": ["firewall rule", "NIPS", "NIDS", "network tap", "SPAN port",
            "jump box", "jump server", "screened subnet", "permit rule",
            "deny rule", "rule set", "anomaly-based", "signature-based",
            "heuristic", "in-line", "inline", "device placement",
            "geofencing application"],
    "3.3": ["checksum", "file integrity", "digital fingerprint", "hash value",
            "geofencing", "human-readable", "non-human-readable", "binary data",
            "AES-256", "encryption standard", "data classification",
            "trade secret", "intellectual property"],
    "3.4": ["hot site", "cold site", "warm site", "backup server",
            "immutable backup", "offline backup", "snapshot", "replication",
            "RPO", "RTO", "generator", "UPS", "redundancy", "clustering",
            "load balancing", "restore"],
    "4.1": ["site survey", "heat map", "WPA3", "MDM", "BYOD", "COPE", "CYOD",
            "input validation", "secure cookie", "code signing", "sandbox",
            "secure baseline", "hardening"],
    "4.2": ["asset inventory", "asset tag", "procurement", "decommission",
            "data retention", "sanitize", "certificate of destruction",
            "enumeration"],
    "4.5": ["DMARC", "DKIM", "SPF", "web filter", "URL filtering",
            "DNS filtering", "NAC", "EDR", "XDR", "group policy", "SELinux",
            "content categorization", "reputation"],
    "4.9": ["network traffic", "traffic capture", "flow record", "log review",
            "SIEM dashboard", "packet analyzer", "endpoint log", "firewall log"],
    "5.1": ["acceptable use", "AUP", "onboarding", "offboarding", "playbook",
            "SDLC", "steering committee", "data owner", "data custodian",
            "data steward", "governance structure"],
    "5.6": ["security awareness", "phishing campaign", "phishing simulation",
            "user training", "insider threat training", "situational awareness"],
}

# --- manual overrides -----------------------------------------------------
# The last word on any question. Add an entry when the classifier files
# something wrongly and you have checked where it belongs. These survive every
# re-run, which is the whole point of keeping tags out of the generated banks.
MANUAL_TAGS = {
    # --- corrections to confident but wrong tags (read by hand 2026-09-14) ---
    "SEC-D1-095": "1.4",   # secure enclaves -- "Secure enclave" is a 1.4 tool
    "SEC-D4-064": "4.9",   # reviewing sent network traffic is a data source, not
                           # vulnerability management
    "SEC-D5-152": "5.1",   # policies/standards/procedures/guidelines is
                           # governance, not the risk process

    # --- the questions the classifier could not place -------------------
    # Every one read and assigned by hand. Where a question could defensibly
    # sit in two objectives the comment says so, because a future reader
    # should not mistake a judgement call for a fact.
    "SEC-D1-037": "1.2",   # logs supporting non-repudiation
    "SEC-D1-076": "1.2",   # controls focused on availability (CIA)

    "SEC-D2-051": "2.5",   # centralised log monitoring -> monitoring
    "SEC-D2-053": "2.5",   # nmap finds open ports vs hardening guidelines
    "SEC-D2-110": "2.4",   # offline brute force against SAM/shadow
    "SEC-D2-114": "2.5",   # telnet on 23 found open -> disable the service
    "SEC-D2-120": "2.5",   # verifying no unnecessary ports/services
    "SEC-D2-134": "2.5",   # Windows log file for a tool's errors -> monitoring
    "SEC-D2-147": "2.5",   # compromised host, immediate action -> isolation
    "SEC-D2-165": "2.4",   # SQLi query run in a pen test -> injection attack
                           # (2.3 would be defensible: SQLi as a vuln type)
    "SEC-D2-169": "2.3",   # Cydia on iPhone -> jailbreaking
    "SEC-D2-173": "2.5",   # ACL to block SSH between segments

    "SEC-D3-090": "3.3",   # comparing files to an original -> hashing
    "SEC-D3-141": "3.1",   # smart lighting/thermostats -> IoT
    "SEC-D3-164": "3.3",   # why hashing cannot store retrievable data
    "SEC-D3-173": "3.1",   # enforcing network segmentation
                           # (3.2 security zones is arguable)
    "SEC-D3-210": "3.1",   # common IoT security issues

    "SEC-D4-066": "4.9",   # counting occurrences in a log file
    "SEC-D4-073": "4.8",   # forensic artefacts beyond drives and files
    "SEC-D4-075": "4.8",   # browsing history from a forensic image
    "SEC-D4-079": "4.8",   # validating forensic attestation
    "SEC-D4-084": "4.8",   # reasons to have an incident response plan
    "SEC-D4-085": "4.2",   # when data recovery is not possible -> sanitisation
    "SEC-D4-108": "4.2",   # RFID tags on equipment -> asset tracking
    "SEC-D4-155": "4.3",   # best insight into vulnerabilities -> credentialed scan
    "SEC-D4-195": "4.3",   # technical controls addressing a vulnerability
    "SEC-D4-199": "4.5",   # reading a Cisco ACL -> firewall rules
    "SEC-D4-210": "4.2",   # devices tampered with before delivery -> procurement

    "SEC-D5-001": "5.4",   # customer data breach -> privacy consequences
    "SEC-D5-033": "5.1",   # setting an encryption standard
    "SEC-D5-049": "5.3",   # agreement protecting proprietary data -> NDA
    "SEC-D5-058": "5.2",   # the possibility of a risk occurring -> likelihood
    "SEC-D5-089": "5.2",   # probability and impact rate risk
    "SEC-D5-117": "5.2",   # breach every four years at $250k -> ALE/ARO
    "SEC-D5-158": "5.3",   # third-party/procurement risk
    "SEC-D5-159": "5.2",   # patching at once -> mitigation strategy
    "SEC-D5-169": "5.2",   # financial cost of a breach -> impact
    "SEC-D5-221": "5.6",   # rogue keyboard spotted -> anomalous behaviour
                           # (5.5 investigation is arguable)
}


def parse_objectives(path):
    """-> {objective_id: {"domain": "2.0", "directive": str, "terms": [str]}}"""
    text = path.read_text(encoding="utf-8", errors="replace")
    blocks = re.split(r"^## OBJECTIVE ", text, flags=re.M)[1:]
    out = {}
    for block in blocks:
        oid = re.match(r"([0-9]+\.[0-9]+)", block)
        if not oid:
            continue
        oid = oid.group(1)
        body = block.split("## ", 1)[0]
        dom = re.search(r'domain_id:\s*"([^"]+)"', body)
        directive = re.search(r'directive_exact:\s*"([^"]+)"', body)
        terms = re.findall(r'^\s*(?:-\s*)?term:\s*"([^"]+)"', body, re.M)
        out[oid] = {
            "domain": dom.group(1) if dom else oid.split(".")[0] + ".0",
            "directive": directive.group(1) if directive else "",
            "terms": terms,
        }
    return out


def aliases(term):
    """"Single loss expectancy (SLE)" -> ["single loss expectancy", "SLE"].

    The acronym is kept case-sensitive so "SLE" does not match inside a word,
    while the phrase is matched case-insensitively.
    """
    out = []
    m = re.match(r"^(.*?)\s*\(([^)]+)\)\s*$", term)
    if m:
        phrase, acro = m.group(1).strip(), m.group(2).strip()
        if phrase:
            out.append(("phrase", phrase))
        # Only treat it as an acronym if it actually looks like one.
        if re.fullmatch(r"[A-Za-z0-9./-]{2,12}", acro) and acro.upper() == acro:
            out.append(("acronym", acro))
        elif acro:
            out.append(("phrase", acro))
    else:
        # "Allow lists/deny lists" -> both halves, plus the whole thing.
        out.append(("phrase", term))
        if "/" in term and len(term) > 12:
            for part in term.split("/"):
                part = part.strip()
                if len(part) >= 5:
                    out.append(("phrase", part))
    return out


def build_index(objectives):
    """Per domain: {objective: [(kind, needle, weight)]}, weighted by rarity."""
    per_domain = defaultdict(lambda: defaultdict(list))
    for oid, meta in objectives.items():
        for term in meta["terms"]:
            if term.strip().lower() in STOP_TERMS:
                continue
            for kind, needle in aliases(term):
                if kind == "phrase" and len(needle) < 5:
                    continue
                per_domain[meta["domain"]][oid].append((kind, needle))
    # Alias terms join their objective's list. They are deliberately specific,
    # so they get the same treatment as any other rare term.
    for oid, extra in ALIASES.items():
        if oid not in objectives:
            continue
        domain = objectives[oid]["domain"]
        for needle in extra:
            kind = "acronym" if re.fullmatch(r"[A-Z0-9.+-]{2,12}", needle) else "phrase"
            per_domain[domain][oid].append((kind, needle))

    indexed = {}
    for domain, by_obj in per_domain.items():
        # How many objectives in this domain use each needle?
        spread = Counter()
        for oid, needles in by_obj.items():
            for _, needle in set(needles):
                spread[needle.lower()] += 1
        indexed[domain] = {}
        for oid, needles in by_obj.items():
            scored = []
            for kind, needle in sorted(set(needles)):
                n = spread[needle.lower()]
                words = len(needle.split())
                weight = (1.0 / n) * (1.0 + 0.6 * (words - 1))
                if kind == "acronym":
                    weight *= 1.4          # acronyms are precise
                scored.append((kind, needle, weight))
            indexed[domain][oid] = scored
    return indexed


def load_bank(n):
    path = QUIZ_DIR / "questions" / f"domain{n}.js"
    src = path.read_text(encoding="utf-8", errors="replace")
    # Anchor on the assignment itself: the first "[" after window.QUESTION_BANKS
    # is the ["domainN"] subscript, not the array.
    assign = re.search(r'window\.QUESTION_BANKS\[\s*"domain%d"\s*\]\s*=\s*' % n, src)
    if not assign:
        raise SystemExit(f"{path.name}: could not find the bank assignment")
    start = src.index("[", assign.end() - 1)
    depth, end = 0, None
    for i, ch in enumerate(src[start:], start):
        if ch == "[":
            depth += 1
        elif ch == "]":
            depth -= 1
            if depth == 0:
                end = i + 1
                break
    return json.loads(src[start:end])


def count_hits(kind, needle, strong, weak):
    if kind == "acronym":
        pat = re.compile(r"(?<![A-Za-z0-9])" + re.escape(needle) + r"(?![A-Za-z0-9])")
        return len(pat.findall(strong)) * 2 + len(pat.findall(weak))
    pat = re.compile(r"(?<![a-z])" + re.escape(needle.lower()) + r"(?![a-z])")
    return len(pat.findall(strong.lower())) * 2 + len(pat.findall(weak.lower()))


def classify(q, candidates):
    strong = q["question"] + " \n " + " \n ".join(q.get("answers", []))
    weak = q.get("explanation", "") + " " + q.get("exhibit", "")
    scores, evidence = {}, {}
    for oid, needles in candidates.items():
        total, matched = 0.0, []
        for kind, needle, weight in needles:
            hits = count_hits(kind, needle, strong, weak)
            if hits:
                # A long, specific term matching is much better evidence than a
                # short common one matching repeatedly, so length drives the
                # score and repeats only nudge it. This is what settles clashes
                # like "CIA" (1.2) against "maintenance window" (1.3).
                specificity = 1.0 + 0.35 * max(0, len(needle.split()) - 1)
                total += weight * specificity * (1 + 0.2 * (hits - 1))
                matched.append(needle)
        scores[oid] = total
        evidence[oid] = matched
    ranked = sorted(scores.items(), key=lambda kv: -kv[1])
    best, best_score = ranked[0]
    runner_up, second = (ranked[1] if len(ranked) > 1 else ("", 0.0))
    margin = best_score - second
    # One bare word is not evidence. A confident tag needs a multi-word phrase,
    # an acronym, or at least two distinct terms from the same objective --
    # otherwise a single stray "Cloud" or "Wireless" decides the cluster.
    hits = evidence[best]
    specific = any(len(h.split()) > 1 or h.isupper() for h in hits) or len(hits) >= 2
    if best_score >= 1.2 and specific and \
            (margin >= 0.6 or best_score >= 2.5 * max(second, 0.01)):
        conf = "high"
    elif best_score >= 0.6:
        conf = "low"
    else:
        conf = "none"
    return {
        "objective": best if conf != "none" else "",
        "confidence": conf,
        "score": round(best_score, 2),
        "runnerUp": runner_up,
        "runnerUpScore": round(second, 2),
        "matched": evidence[best][:6],
        "runnerUpMatched": evidence.get(runner_up, [])[:4],
    }


def main():
    wanted = [int(a) for a in sys.argv[1:]] or [1, 2, 3, 4, 5]
    objectives = parse_objectives(OBJECTIVES_MD)
    index = build_index(objectives)

    results, per_domain_counts, needs_review = {}, defaultdict(Counter), []
    for n in wanted:
        bank = load_bank(n)
        domain = f"{n}.0"
        candidates = index[domain]
        for q in bank:
            verdict = classify(q, candidates)
            if q["id"] in MANUAL_TAGS:
                verdict = {**verdict, "objective": MANUAL_TAGS[q["id"]],
                           "confidence": "manual", "matched": ["(manual override)"]}
            results[q["id"]] = verdict
            key = verdict["objective"] or "unsorted"
            per_domain_counts[domain][key] += 1
            if verdict["confidence"] not in ("high", "manual"):
                needs_review.append((q["id"], q["question"], verdict))

    # ---- questions/objectives.js -------------------------------------------
    meta = {oid: {"name": objectives[oid]["directive"], "domain": objectives[oid]["domain"]}
            for oid in sorted(objectives)}
    tags = {qid: {"o": v["objective"], "c": v["confidence"]}
            for qid, v in sorted(results.items()) if v["objective"]}
    out = QUIZ_DIR / "questions" / "objectives.js"
    out.write_text(
        "/* CompTIA Security+ SY0-701 -- objective tags per question.\n"
        "   GENERATED by tools/classify_objectives.py -- do not hand-edit;\n"
        "   add corrections to MANUAL_TAGS in that script instead.\n"
        f"   {len(tags)} of {len(results)} questions tagged.\n"
        "   o = objective id, c = confidence (high|low). Untagged questions\n"
        "   appear in the app under 'Unsorted' and are listed in\n"
        "   tools/objective-review.md. */\n"
        "window.OBJECTIVE_META = " + json.dumps(meta, indent=2) + ";\n"
        "window.QUESTION_OBJECTIVES = " + json.dumps(tags, indent=2) + ";\n",
        encoding="utf-8")

    # ---- tools/objective-review.md -----------------------------------------
    lines = ["# Objective tagging review", "",
             f"Generated by `tools/classify_objectives.py` for domain(s) {wanted}.", ""]
    total = len(results)
    high = sum(1 for v in results.values() if v["confidence"] in ("high", "manual"))
    low = sum(1 for v in results.values() if v["confidence"] == "low")
    none = total - high - low
    lines += [f"**{total} questions: {high} high confidence, {low} low, {none} unsorted.**", ""]
    for domain in sorted(per_domain_counts):
        lines += [f"## Domain {domain}", "", "| Objective | Questions | Directive |",
                  "| --- | --- | --- |"]
        counts = per_domain_counts[domain]
        for oid in sorted(k for k in counts if k != "unsorted"):
            lines.append(f"| {oid} | {counts[oid]} | {objectives[oid]['directive']} |")
        if counts["unsorted"]:
            lines.append(f"| unsorted | {counts['unsorted']} | needs a human |")
        lines.append("")
    lines += ["## Needs checking", "",
              "Low-confidence or unsorted questions, with the top two candidates.", ""]
    for qid, stem, v in needs_review:
        lines += [f"- **{qid}** [{v['confidence']}] {stem[:150]}",
                  f"  - best: {v['objective'] or '(none)'} ({v['score']}) via {v['matched']}",
                  f"  - next: {v['runnerUp']} ({v['runnerUpScore']}) via {v['runnerUpMatched']}"]
    (QUIZ_DIR / "tools" / "objective-review.md").write_text("\n".join(lines) + "\n",
                                                            encoding="utf-8")

    print(f"{total} questions classified: {high} high, {low} low, {none} unsorted")
    for domain in sorted(per_domain_counts):
        counts = per_domain_counts[domain]
        spread = ", ".join(f"{k}:{counts[k]}" for k in sorted(counts))
        print(f"  domain {domain}: {spread}")
    print(f"wrote {out.relative_to(QUIZ_DIR)} and tools/objective-review.md")


if __name__ == "__main__":
    main()
